In [1]:
#@title Parameters

# @markdown <h3>Main Parameters</h3>
DATASET_NAME = "EMOTION" #@param ["MPQA-T", "MPQA-P", "MPQA-I", "AGNEWS", "AMZN-EN", "EMOTION"]
AFL_APPROACH = "FINE-TUNING" #@param ["FINE-TUNING", "IN-CONTEXT"]
BASE_MODEL = "FLAN-T5" #@param ["BART", "FLAN-T5", "Uncharted"]
# @markdown &emsp; ↳ Model name and learning rate will be automatically configured if anything other than uncharted is selected. If uncharted is selected, the model name and learning rate need to be configured manually.
AFL_METHOD = "Random" #@param ["Random", "Rep(En)", "Rep(En)-Un", "Rep(En)-Rep(Sc)", "Rep(En)-Rep(En)", "Rep(En)-UnRep", "Rep(En)-ClUn(Sc)", "Rep(En)-ClUn(En)", "Uncharted"]
# @markdown &emsp; ↳ Embedding and sampling methods will be automatically configured if anything other than uncharted is selected. If uncharted is selected, the embedding and sampling methods need to be configured manually.
SAMPLING_ITERATIONS = 1 #@param {type:'slider', min:1, max:32, step:1}
NUMBER_OF_SAMPLES_PER_ITERATION = 100 #@param {type:'slider', min:3, max:100, step:1}
# @markdown &emsp; ↳ M in paper; K = SAMPLING_ITERATIONS * M

# @markdown <br/> <h3> Other Parameters </h3>
RUNTIME_TYPE = 'CONDA' #@param ["COLAB", "CONDA"]
EXPERIMENT_NAME = 'EMOTION_FLANT5_RANDOM_100'
MAX_NEW_TOKENS = 5 #@param {type:'slider', min:1, max:20, step:1}
LEARNING_RATE = 1e-4 #@param {"type": "number"}
FP16 = False
LOCAL_RANK = -1
FP16_OPT_LEVEL = 'O1'
FP16_FULL_EVAL = False
PER_DEVICE_TRAIN_BATCH_SIZE = 10 #@param {type: "integer"}
PER_DEVICE_VAL_BATCH_SIZE = 64 #@param {type: "integer"}
PER_DEVICE_VAL_BATCH_SIZE_EMBEDDING = 64 #@param {type: "integer"}
LOGGING_STRATEGY = 'epoch'
EVAL_STRATEGY = 'epoch'
SAVE_STRATEGY = 'epoch'
LOAD_BEST_MODEL_AT_END = True
METRIC_FOR_BEST_MODEL = 'eval_main_metric'
NUM_TRAIN_EPOCHS = 1000
EARLY_STOPPING = 20 # Set 0 to disable
SEED = 0
MODEL_NAME = "facebook/bart-base" # @param ["facebook/bart-base","t5-small","t5-base","t5-large","google/flan-t5-small","google/flan-t5-base","google/flan-t5-large"] {"allow-input":true}
EMBEDDING_METHOD_FIRST_ITERATION = "FLAN-T5-ENCODER" #@param ["BART-ENCODER", "BART-SCORES", "BART-SCORES+ENCODER", "T5-ENCODER", "FLAN-T5-ENCODER", "FLAN-T5-SCORES", "FLAN-T5-SCORE+ENCODER"]
EMBEDDING_METHOD_SECOND_ITERATION_PLUS = "SAME_AS_BEFORE" #@param ["SAME_AS_BEFORE", "SCORES", "SCORES+FLAN-T5", "BART", "T5", "FLAN-T5"]
EMBEDDING_PREFIX = None
SAMPLING_METHOD_FIRST_ITERATION = "KMEANS_REPRESENTATIVE" #@param ["BALANCED", "RANDOM", "KMEANS_RANDOM", "KMEANS_REPRESENTATIVE"]
SAMPLING_METHOD_SECOND_ITERATION_PLUS = "SAME_AS_BEFORE" #@param ["SAME_AS_BEFORE", "ENTROPY_THEN_KMEANS_REPRESENTATIVE", "KMEANS_REPRESENTATIVE_THEN_ENTROPY", "ENTROPY", "BALANCED", "RANDOM", "KMEANS_RANDOM", "KMEANS_REPRESENTATIVE"]
REPEAT_SAMPLING = 5 #@param {type:'slider', min:1, max:10, step:1}
# @markdown &emsp; ↳ Repeat the experiment with different sampling seeds ∊ [0, REPEAT_SAMPLING)
KMEANS_INIT = 'random' #@param ["k-means++", "random"]
KMEANS_CENTROID_SEEDS = 10 #@param {type:'slider', min:1, max:10, step:1}
KMEANS_ALGORITHM = 'lloyd' #@param ["lloyd", "elkan"]
UNREP_ALPHA = 10
RESET_MODEL_AFTER_EACH_ITERATION = True #@param {type:"boolean"}
PREDICT_WITH_GENERATE = True #@param {type:"boolean"}
STORE_RESULTS = ['eval_main_metric'] # Array of metrics' names: save and store results of a suite of notebooks
# ↳ Example: ['eval_main_metric', 'eval_agnews_macro_f1']
SHOW_VAL_PREDICTIONS = True #@param {type:"boolean"}
MAX_FOLDS = 1

# Checkpoints
SKIP_SAMPLING_SEEDS = 0 # Skip the first few seeds if things went wrong during the previous runtime.
RESTORE_CHECKPOINT_FROM_FILE = True #@param {type:"boolean"}
# If restore from file was false, use the following checkpoint variables:
INIT_FOLDS_VAL_LOG = [[]]
INIT_FOLDS_TEST_LOG = [[]]
INIT_PREDS_TEXTS_VAL_LIST = [[]]
INIT_TARGETS_TEXTS_VAL_LIST = [ ]
INIT_SAMPLED_LIST = [[]]

# IDs
TYPE_IDS = ['agreement', 'argue', 'intention', 'sentiment']
POLARITY_IDS = ['negative', 'positive']
INTENSITY_IDS = ['slight', 'low', 'medium', 'high', 'extreme']
AGNEWS_IDS = ['world', 'sports', 'business', 'science']
AMZN_IDS = ['1', '2', '3', '4', '5']
EMOTION_IDS = ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

# @markdown <br/> <h3> Dataset Links </h3>
# @markdown *(Either URLs or local file paths)* <br/>

# @markdown **MPQA Type**
mpqa_t_train_link = '../data/afl-subset/t_train.csv' #@param {type: "string"}
mpqa_t_val_link   = '../data/afl-subset/t_val.csv' #@param {type: "string"}
mpqa_t_test_link  = '../data/afl-subset/t_test.csv' #@param {type: "string"}

# @markdown **MPQA Polarity**
mpqa_p_train_link = '../data/afl-subset/p_train.csv' #@param {type: "string"}
mpqa_p_val_link   = '../data/afl-subset/p_val.csv' #@param {type: "string"}
mpqa_p_test_link  = '../data/afl-subset/p_test.csv' #@param {type: "string"}

# @markdown **MPQA Intensity**
mpqa_i_train_link = '../data/afl-subset/i_train.csv' #@param {type: "string"}
mpqa_i_val_link   = '../data/afl-subset/i_val.csv' #@param {type: "string"}
mpqa_i_test_link  = '../data/afl-subset/i_test.csv' #@param {type: "string"}

# @markdown **Emotion**
emotion_train_link = 'hf://datasets/dair-ai/emotion/split/train-00000-of-00001.parquet' #@param {type: "string"}
emotion_val_link   = 'hf://datasets/dair-ai/emotion/split/validation-00000-of-00001.parquet' #@param {type: "string"}
emotion_test_link  = 'hf://datasets/dair-ai/emotion/split/test-00000-of-00001.parquet' #@param {type: "string"}


# @markdown **AG News**
agnews_trainval_link = '' #@param {type: "string"}
agnews_test_link     = '' #@param {type: "string"}

# @markdown **Amazon Reviews**
amzn_train_link = '' #@param {type: "string"}
amzn_val_link   = '' #@param {type: "string"}
amzn_test_link  = '' #@param {type: "string"}

In [2]:
import pandas as pd

splits = {'train': 'split/train-00000-of-00001.parquet', 'validation': 'split/validation-00000-of-00001.parquet', 'test': 'split/test-00000-of-00001.parquet'}
df = pd.read_parquet("hf://datasets/dair-ai/emotion/" + splits["train"])

/venv/afl-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
df

                                                    text  label
0                                i didnt feel humiliated      0
1      i can go from feeling so hopeless to so damned...      0
2       im grabbing a minute to post i feel greedy wrong      3
3      i am ever feeling nostalgic about the fireplac...      2
4                                   i am feeling grouchy      3
...                                                  ...    ...
15995  i just had a very brief time in the beanbag an...      0
15996  i am now turning and i feel pathetic that i am...      0
15997                     i feel strong and good overall      1
15998  i feel like this was such a rude comment and i...      3
15999  i know a lot but i feel so stupid because i ca...      0

[16000 rows x 2 columns]

In [4]:
NUMBER_OF_SAMPLES_PER_ITERATION = [NUMBER_OF_SAMPLES_PER_ITERATION] * SAMPLING_ITERATIONS if type(NUMBER_OF_SAMPLES_PER_ITERATION).__name__ != 'list' else NUMBER_OF_SAMPLES_PER_ITERATION # Can be a list too; the length of the list should be equal to the number of iterations
PER_DEVICE_TRAIN_BATCH_SIZE = min(PER_DEVICE_TRAIN_BATCH_SIZE, min(NUMBER_OF_SAMPLES_PER_ITERATION))

In [5]:
# Set the parameters that can be derived from the main parameters

if BASE_MODEL == 'BART':
    MODEL_NAME = 'facebook/bart-base'
    LEARNING_RATE = 5e-5
elif BASE_MODEL == 'FLAN-T5':
    MODEL_NAME = 'google/flan-t5-base'
    LEARNING_RATE = 1e-4

if AFL_METHOD == 'Random':
    SAMPLING_METHOD_FIRST_ITERATION = 'RANDOM'
    NUMBER_OF_SAMPLES_PER_ITERATION *= SAMPLING_ITERATIONS
    SAMPLING_ITERATIONS = 1

elif AFL_METHOD == 'Rep(En)':
    if BASE_MODEL == 'BART':
        EMBEDDING_METHOD_FIRST_ITERATION = 'BART-ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        NUMBER_OF_SAMPLES_PER_ITERATION *= SAMPLING_ITERATIONS
        SAMPLING_ITERATIONS = 1
    elif BASE_MODEL == 'FLAN-T5':
        EMBEDDING_METHOD_FIRST_ITERATION = 'FLAN-T5-ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        NUMBER_OF_SAMPLES_PER_ITERATION *= SAMPLING_ITERATIONS
        SAMPLING_ITERATIONS = 1

elif AFL_METHOD == 'Rep(En)-Un':
    if BASE_MODEL == 'BART':
        EMBEDDING_METHOD_FIRST_ITERATION = 'BART-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'BART-SCORES'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'ENTROPY'
    elif BASE_MODEL == 'FLAN-T5':
        EMBEDDING_METHOD_FIRST_ITERATION = 'FLAN-T5-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'FLAN-T5-SCORES'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'ENTROPY'

elif AFL_METHOD == 'Rep(En)-Rep(Sc)':
    if BASE_MODEL == 'BART':
        EMBEDDING_METHOD_FIRST_ITERATION = 'BART-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'BART-SCORES'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE'
    elif BASE_MODEL == 'FLAN-T5':
        EMBEDDING_METHOD_FIRST_ITERATION = 'FLAN-T5-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'FLAN-T5-SCORES'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE'

elif AFL_METHOD == 'Rep(En)-Rep(En)':
    if BASE_MODEL == 'BART':
        EMBEDDING_METHOD_FIRST_ITERATION = 'BART-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'BART-ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE'
    elif BASE_MODEL == 'FLAN-T5':
        EMBEDDING_METHOD_FIRST_ITERATION = 'FLAN-T5-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'FLAN-T5-ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE'

elif AFL_METHOD == 'Rep(En)-UnRep':
    if BASE_MODEL == 'BART':
        EMBEDDING_METHOD_FIRST_ITERATION = 'BART-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'BART-SCORES+ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'ENTROPY_THEN_KMEANS_REPRESENTATIVE'
    elif BASE_MODEL == 'FLAN-T5':
        EMBEDDING_METHOD_FIRST_ITERATION = 'FLAN-T5-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'FLAN-T5-SCORES+ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'ENTROPY_THEN_KMEANS_REPRESENTATIVE'

elif AFL_METHOD == 'Rep(En)-ClUn(Sc)':
    if BASE_MODEL == 'BART':
        EMBEDDING_METHOD_FIRST_ITERATION = 'BART-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'BART-SCORES'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE_THEN_ENTROPY'
    elif BASE_MODEL == 'FLAN-T5':
        EMBEDDING_METHOD_FIRST_ITERATION = 'FLAN-T5-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'FLAN-T5-SCORES'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE_THEN_ENTROPY'

elif AFL_METHOD == 'Rep(En)-ClUn(En)':
    if BASE_MODEL == 'BART':
        EMBEDDING_METHOD_FIRST_ITERATION = 'BART-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'BART-SCORES+ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE_THEN_ENTROPY'
    elif BASE_MODEL == 'FLAN-T5':
        EMBEDDING_METHOD_FIRST_ITERATION = 'FLAN-T5-ENCODER'
        EMBEDDING_METHOD_SECOND_ITERATION_PLUS = 'FLAN-T5-SCORES+ENCODER'
        SAMPLING_METHOD_FIRST_ITERATION = 'KMEANS_REPRESENTATIVE'
        SAMPLING_METHOD_SECOND_ITERATION_PLUS = 'KMEANS_REPRESENTATIVE_THEN_ENTROPY'

In [6]:
!pwd
%mkdir models

/workspace/active-fewshot-learning/EMOTION_FLANT5_RANDOM_K100

In [7]:
!nvidia-smi

Fri Mar 20 15:51:17 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40                     On  |   00000000:E1:00.0 Off |                    0 |
| N/A   51C    P0            155W /  300W |    6041MiB /  46068MiB |     47%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [8]:
if RUNTIME_TYPE == 'COLAB':
    %pip install transformers==4.25.1 datasets --quiet

In [9]:
# To assure deterministic results
import os
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['CUBLAS_WORKSPACE_CONFIG'] = ":4096:8"

In [10]:
import gc
import sys
import json
import time
import random
import itertools
import functools
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq, EarlyStoppingCallback, AutoConfig
from datasets import load_dataset
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, pairwise_distances_argmin_min, confusion_matrix, multilabel_confusion_matrix
from sklearn.utils.random import sample_without_replacement
from sklearn.cluster import KMeans, SpectralClustering
from scipy.special import softmax
from urllib.request import urlopen
import seaborn as sns
import matplotlib.pyplot as plt
import statistics
from datetime import datetime
import logging
from functools import wraps

%matplotlib inline
%config InlineBackend.figure_format='retina'

/venv/afl-env/lib/python3.10/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/venv/afl-env/lib/python3.10/site-packages/transformers/utils/generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(

In [11]:
# Start timer

start_time = datetime.now()

In [12]:
# Support for third-party widgets

if RUNTIME_TYPE == 'COLAB':
    from google.colab import output
    output.enable_custom_widget_manager()

In [13]:
# Setup device

device_string = 'cuda' if torch.cuda.is_available() else 'cpu'
device_hf = 0 if torch.cuda.is_available() else -1
device = torch.device(device_string)
print("Device:", device)
NUM_WORKERS = 0

Device: cuda

In [14]:
# Callbacks

CALLBACKS = []
if EARLY_STOPPING > 0:
    CALLBACKS.append(EarlyStoppingCallback(EARLY_STOPPING))

In [15]:
def set_seed():
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    torch.cuda.manual_seed(SEED)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True

# Restore Last Checkpoint

In [16]:
if RESTORE_CHECKPOINT_FROM_FILE:
    try:
        with open(f'results/{EXPERIMENT_NAME.replace(".ipynb", "")}_checkpoint.json') as checkpoint_file:
            checkpoint = json.load(checkpoint_file)
            INIT_FOLDS_VAL_LOG = checkpoint['INIT_FOLDS_VAL_LOG']
            INIT_FOLDS_TEST_LOG = checkpoint['INIT_FOLDS_TEST_LOG']
            INIT_PREDS_TEXTS_VAL_LIST = checkpoint['INIT_PREDS_TEXTS_VAL_LIST']
            INIT_SAMPLED_LIST = checkpoint['INIT_SAMPLED_LIST']

            INIT_FOLDS_VAL_LOG[-1].pop()
            INIT_FOLDS_TEST_LOG[-1].pop()
            INIT_PREDS_TEXTS_VAL_LIST[-1].pop()
            INIT_SAMPLED_LIST[-1].pop() 
            SKIP_SAMPLING_SEEDS = len(INIT_FOLDS_VAL_LOG[-1])
            print(f"Skipped the first {SKIP_SAMPLING_SEEDS} seeds.")
    except Exception as e:
        None

# Preparing the dataset

In [17]:
# Classes

TYPE_CLASSES = ['agreement', 'arguing', 'intention', 'sentiment']
POLARITY_CLASSES = ['negative', 'positive']
INTENSITY_CLASSES = ['low', 'low medium', 'medium', 'medium high', 'high']
EMOTION_CLASSES = [0, 1, 2, 3, 4, 5] # ['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']
AGNEWS_CLASSES = [1, 2, 3, 4]
AMZN_CLASSES = [1, 2, 3, 4, 5]

NUM_TYPE_CLASSES = len(TYPE_CLASSES)
NUM_POLARITY_CLASSES = len(POLARITY_CLASSES)
NUM_INTENSITY_CLASSES = 5
NUM_INTENSITY_UNITS = 3
NUM_EMOTION_CLASSES = len(EMOTION_CLASSES)
NUM_AGNEWS_CLASSES = len(AGNEWS_CLASSES)
NUM_AMZN_CLASSES = len(AMZN_CLASSES)

if DATASET_NAME == 'MPQA-T':
    CLASSES = TYPE_CLASSES
    NUM_CLASSES = NUM_TYPE_CLASSES
    CLASS_IDS = TYPE_IDS
elif DATASET_NAME == 'MPQA-P':
    CLASSES = POLARITY_CLASSES
    NUM_CLASSES = NUM_POLARITY_CLASSES
    CLASS_IDS = POLARITY_IDS
elif DATASET_NAME == 'MPQA-I':
    CLASSES = INTENSITY_CLASSES
    NUM_CLASSES = NUM_INTENSITY_CLASSES
    CLASS_IDS = INTENSITY_IDS
elif DATASET_NAME == 'EMOTION':
    CLASSES = EMOTION_CLASSES
    NUM_CLASSES = NUM_EMOTION_CLASSES
    CLASS_IDS = EMOTION_IDS
elif DATASET_NAME == 'AGNEWS':
    CLASSES = AGNEWS_CLASSES
    NUM_CLASSES = NUM_AGNEWS_CLASSES
    CLASS_IDS = AGNEWS_IDS
elif DATASET_NAME.startswith('AMZN'):
    CLASSES = AMZN_CLASSES
    NUM_CLASSES = NUM_AMZN_CLASSES
    CLASS_IDS = AMZN_IDS
else:
    CLASSES = []
    NUM_CLASSES = 0
    CLASS_IDS = []

In [18]:
# Create a map for class ids and class names

type_classname2classindex = {
    'agreement': 0,
    'arguing':   1,
    'intention': 2,
    'sentiment': 3,
}
type_classname2classid = {
    'agreement': TYPE_IDS[0],
    'arguing':   TYPE_IDS[1],
    'intention': TYPE_IDS[2],
    'sentiment': TYPE_IDS[3],
}
type_classid2classname = {v:k for k, v in type_classname2classid.items()}
type_classid2classindex = {type_classname2classid[k]:v for k, v in type_classname2classindex.items()}

###

polarity_classname2classindex = {
    'negative': 0,
    'positive': 1,
}
polarity_classname2classid = {
    'negative': POLARITY_IDS[0],
    'positive': POLARITY_IDS[1],
}
polarity_classid2classname = {v:k for k, v in polarity_classname2classid.items()}
polarity_classid2classindex = {polarity_classname2classid[k]:v for k, v in polarity_classname2classindex.items()}

###

intensity_classname2classindices = {
    'low':        [0],
    'low medium': [0, 1],
    'medium':        [1],
    'medium high':   [1, 2],
    'high':             [2],
}
intensity_classname2classid = {
    'low':         INTENSITY_IDS[0],
    'low medium':  INTENSITY_IDS[1],
    'medium':      INTENSITY_IDS[2],
    'medium high': INTENSITY_IDS[3],
    'high':        INTENSITY_IDS[4],
}
intensity_classid2classname = {v:k for k, v in intensity_classname2classid.items()}
intensity_classid2classindices = {intensity_classname2classid[k]:v for k, v in intensity_classname2classindices.items()}

###
emotion_classname2classindex = {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
}
emotion_classname2classid = {
    0: EMOTION_IDS[0],
    1: EMOTION_IDS[1],
    2: EMOTION_IDS[2],
    3: EMOTION_IDS[3],
    4: EMOTION_IDS[4],
    5: EMOTION_IDS[5],
}
emotion_classid2classname = {v:k for k, v in emotion_classname2classid.items()}
emotion_classid2classindex = {emotion_classname2classid[k]:v for k, v in emotion_classname2classindex.items()}

###

agnews_classname2classindex = {
    1: 0,
    2: 1,
    3: 2,
    4: 3,
}
agnews_classname2classid = {
    1: AGNEWS_IDS[0],
    2: AGNEWS_IDS[1],
    3: AGNEWS_IDS[2],
    4: AGNEWS_IDS[3],
}
agnews_classid2classname = {v:k for k, v in agnews_classname2classid.items()}
agnews_classid2classindex = {agnews_classname2classid[k]:v for k, v in agnews_classname2classindex.items()}

###

amzn_classname2classindex = {
    1: 0,
    2: 1,
    3: 2,
    4: 3,
    5: 4,
}
amzn_classname2classid = {
    1: AMZN_IDS[0],
    2: AMZN_IDS[1],
    3: AMZN_IDS[2],
    4: AMZN_IDS[3],
    5: AMZN_IDS[4],
}
amzn_classid2classname = {v:k for k, v in amzn_classname2classid.items()}
amzn_classid2classindex = {amzn_classname2classid[k]:v for k, v in amzn_classname2classindex.items()}

In [19]:
# Labels Distribution

def count_labels(Y=None, Y_train=None, Y_val=None, Y_test=None):

    if Y==None:

        count_dict = {}
        for y in Y_train:
            count_dict[y] = count_dict.get(y, 0) + 1
        print('Train Labels distribution:', count_dict)

        count_dict = {}
        for y in Y_val:
            count_dict[y] = count_dict.get(y, 0) + 1
        print('Validation Labels distribution:', count_dict)

        count_dict = {}
        for y in Y_test:
            count_dict[y] = count_dict.get(y, 0) + 1
        print('Test Labels distribution:', count_dict)

        Y = Y_train + Y_val + Y_test

    count_dict = {}
    for y in Y:
        count_dict[y] = count_dict.get(y, 0) + 1
    print('Labels distribution:', count_dict)

In [20]:
# Decompose X and y

def decompose_mpqa(dataset):
    if AFL_APPROACH == "FINE-TUNING":
        X = [i for i in dataset.input]
    elif AFL_APPROACH == "IN-CONTEXT":
        X = ['{ ' + f'{" ".join(i.splitlines())}' + ' } :' for i in dataset.input]

    if DATASET_NAME == 'MPQA-T':
        y = [i.replace(TYPE_CLASSES[0], TYPE_IDS[0]) \
              .replace(TYPE_CLASSES[1], TYPE_IDS[1]) \
              .replace(TYPE_CLASSES[2], TYPE_IDS[2]) \
              .replace(TYPE_CLASSES[3], TYPE_IDS[3]) for i in dataset.output]
    elif DATASET_NAME == 'MPQA-P':
        y = [i.replace(POLARITY_CLASSES[0], POLARITY_IDS[0]) \
              .replace(POLARITY_CLASSES[1], POLARITY_IDS[1]) for i in dataset.output]
    elif DATASET_NAME == 'MPQA-I':
        # Add special characters to avoid conflicts
        y = [('!'+i+'!').replace('!'+INTENSITY_CLASSES[0]+'!', INTENSITY_IDS[0]) \
                        .replace('!'+INTENSITY_CLASSES[1]+'!', INTENSITY_IDS[1]) \
                        .replace('!'+INTENSITY_CLASSES[2]+'!', INTENSITY_IDS[2]) \
                        .replace('!'+INTENSITY_CLASSES[3]+'!', INTENSITY_IDS[3]) \
                        .replace('!'+INTENSITY_CLASSES[4]+'!', INTENSITY_IDS[4]) for i in dataset.output]
    return X, y

def decompose_emotion(dataset):
    if AFL_APPROACH == "FINE-TUNING":
        X = [i for i in dataset.text]
    elif AFL_APPROACH == "IN-CONTEXT":
        X = ['{ ' + f'{" ".join(i.splitlines())}' + ' } :' for i in dataset.text]
    y = [EMOTION_IDS[i] for i in dataset.label]
    return X, y

def decompose_agnews(dataset):
    if AFL_APPROACH == "FINE-TUNING":
        X = [f'{title} | {desc}' for title, desc in zip(dataset.Title, dataset.Description)]
    elif AFL_APPROACH == "IN-CONTEXT":
        X = ['{ ' + f'{" ".join(title.splitlines())} | {" ".join(desc.splitlines())}' + ' } :' for title, desc in zip(dataset.Title, dataset.Description)]
    y = [AGNEWS_IDS[i-1] for i in dataset['Class Index']]
    return X, y

def decompose_amzn(dataset, filter_lang='en'):
    X = []
    y = []
    for title, body, lang, stars in zip(dataset.review_title, dataset.review_body, dataset.language, dataset.stars):
        if lang == filter_lang:
            if AFL_APPROACH == "FINE-TUNING":
                X = X + [f'{title} | {body}'[:900]]
            elif AFL_APPROACH == "IN-CONTEXT":
                X = X + ['{ ' + f'{" ".join(title.splitlines())} | {" ".join(body.splitlines())}'[:900] + ' } :']
            y = y + [AMZN_IDS[stars-1]]
    return X, y

In [21]:
@functools.cache
def pd_read_csv(link):
    if link.startswith("http://") or link.startswith("https://"):
        # Handle URLs
        t = 15
        while True:
            try:
                return pd.read_csv(link)
            except Exception as e:
                print(f"Unsuccessful attempt to download {link}. Waiting for {t}s.")
                time.sleep(t)
                t *= random.random()+1
                t = int(t)
                continue
    else:
        # Handle local file paths
        return pd.read_csv(link)

@functools.cache
def pd_read_parquet(link):
    if link.startswith("http://") or link.startswith("https://") or link.startswith("hf://"):
        # Handle URLs
        t = 15
        while True:
            try:
                return pd.read_parquet(link)
            except Exception as e:
                print(f"Unsuccessful attempt to download {link}. Waiting for {t}s.")
                time.sleep(t)
                t *= random.random()+1
                t = int(t)
                continue
    else:
        # Handle local file paths
        return pd.read_parquet(link)

In [22]:
# Fetch the dataset

def fetch_dataset(dataset_name=DATASET_NAME, fold=0, show_counter=False):

    if dataset_name.startswith('MPQA-'):

        if dataset_name == 'MPQA-T':
            trainset = pd_read_csv(mpqa_t_train_link)
            valset   = pd_read_csv(mpqa_t_val_link)
            testset  = pd_read_csv(mpqa_t_test_link)
        elif dataset_name == 'MPQA-P':
            trainset = pd_read_csv(mpqa_p_train_link)
            valset   = pd_read_csv(mpqa_p_val_link)
            testset  = pd_read_csv(mpqa_p_test_link)
        elif dataset_name == 'MPQA-I':
            trainset = pd_read_csv(mpqa_i_train_link)
            valset   = pd_read_csv(mpqa_i_val_link)
            testset  = pd_read_csv(mpqa_i_test_link)

        X_train, y_train = decompose_mpqa(trainset)
        X_val,   y_val   = decompose_mpqa(valset)
        X_test,  y_test  = decompose_mpqa(testset)

        if show_counter == True:
            count_labels(Y_train=y_train, Y_val=y_val, Y_test=y_test)

    elif dataset_name == 'EMOTION':
        trainset = pd_read_parquet(emotion_train_link)
        valset   = pd_read_parquet(emotion_val_link)
        testset  = pd_read_parquet(emotion_test_link)

        X_train, y_train = decompose_emotion(trainset)
        X_val,   y_val   = decompose_emotion(valset)
        X_test,  y_test  = decompose_emotion(testset)

        if show_counter == True:
            count_labels(Y_train=y_train, Y_val=y_val, Y_test=y_test)
            
    elif dataset_name == 'AGNEWS':

        trainvalset = pd_read_csv(agnews_trainval_link)
        testset     = pd_read_csv(agnews_test_link)

        X_train_val, y_train_val = decompose_agnews(trainvalset)
        X_test,      y_test      = decompose_agnews(testset)

        X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=1200, shuffle=True, stratify=y_train_val, random_state=SEED)

        if show_counter == True:
            count_labels(Y_train=y_train, Y_val=y_val, Y_test=y_test)

    elif dataset_name.startswith('AMZN'):

        filter_lang = dataset_name[-2:].lower()

        trainset = pd_read_csv(amzn_train_link)
        valset   = pd_read_csv(amzn_val_link)
        testset  = pd_read_csv(amzn_test_link)

        X_train, y_train = decompose_amzn(trainset, filter_lang)
        X_val,   y_val   = decompose_amzn(valset,   filter_lang)
        X_test,  y_test  = decompose_amzn(testset,  filter_lang)

        _, X_val, _, y_val = train_test_split(X_val, y_val, test_size=1200, shuffle=True, stratify=y_val, random_state=SEED)

        if show_counter == True:
            count_labels(Y_train=y_train, Y_val=y_val, Y_test=y_test)

    return (X_train, y_train), (X_val, y_val), (X_test, y_test)

In [23]:
# All samples

(X_train, y_train), (X_val, y_val), (X_test, y_test) = fetch_dataset()

print(f'First three samples (out of {len(y_train)+len(y_val)+len(y_test)} = {len(y_train)} + {len(y_val)} + {len(y_test)}):')
for i in range(0, 3):
    print('┌X:', X_train[i])
    print('└y:', y_train[i])

First three samples (out of 20000 = 16000 + 2000 + 2000):
┌X: i didnt feel humiliated
└y: sadness
┌X: i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake
└y: sadness
┌X: im grabbing a minute to post i feel greedy wrong
└y: anger

# Preparing the model and torch dataset

In [24]:
# Load the hf model and tokenizer

def load_tokenizer(model_name=MODEL_NAME):
    tokenizer = AutoTokenizer.from_pretrained(model_name, model_max_length=512)
    return tokenizer

def load_model(model_name=MODEL_NAME):
    model_hf = AutoModelForSeq2SeqLM.from_pretrained(
        model_name, resume_download=True,
        config=AutoConfig.from_pretrained(model_name)
    )

    pytorch_total_params = sum(p.numel() for p in model_hf.parameters() if p.requires_grad)
    print('Number of trainable parameters in base model:', pytorch_total_params)

    return model_hf

In [25]:
tokenizer = load_tokenizer()
model = load_model()

Number of trainable parameters in base model: 247577856

In [26]:
# Show how each class is tokenized

for class_id in CLASS_IDS:
    print(f'{class_id}: {tokenizer(class_id)}')

sadness: {'input_ids': [24784, 1], 'attention_mask': [1, 1]}
joy: {'input_ids': [3922, 1], 'attention_mask': [1, 1]}
love: {'input_ids': [333, 1], 'attention_mask': [1, 1]}
anger: {'input_ids': [11213, 1], 'attention_mask': [1, 1]}
fear: {'input_ids': [2971, 1], 'attention_mask': [1, 1]}
surprise: {'input_ids': [4158, 1], 'attention_mask': [1, 1]}

In [27]:
# Store the first token only

if MODEL_NAME in ['google/flan-t5-base']:
    CLASSES_TOKENS = [tokenizer(class_id).input_ids[0] for class_id in CLASS_IDS]
elif MODEL_NAME in ['facebook/bart-base']:
    CLASSES_TOKENS = [tokenizer(class_id).input_ids[1] for class_id in CLASS_IDS]
else:
    raise Exception('The behavior for new tokenizer needs to be configured.')
print(CLASSES_TOKENS)

[24784, 3922, 333, 11213, 2971, 4158]

In [28]:
if EMBEDDING_METHOD_FIRST_ITERATION in ['BART-ENCODER']:
    emb_tokenizer = load_tokenizer('facebook/bart-base')
if EMBEDDING_METHOD_FIRST_ITERATION in ['T5-ENCODER']:
    emb_tokenizer = load_tokenizer('t5-base')
if EMBEDDING_METHOD_FIRST_ITERATION in ['FLAN-T5-ENCODER']:
    emb_tokenizer = load_tokenizer('google/flan-t5-base')

In [29]:
# Load optimizer

def load_optimizer(model):
    opt_parameters = model.parameters()
    return torch.optim.AdamW(opt_parameters, lr=LEARNING_RATE)

In [30]:
# Tokenize the inputs

@functools.cache
def tokenize_inputs(tokenizer, X, y):
    if type(X) is tuple:
        X = list(X)
        y = list(y)

    Xy_tokenized = tokenizer(X, text_target=y, truncation=True)
    return Xy_tokenized

def tokenize_and_show_inputs(tokenizer, X='', y=''):
    print("\nPretokenized examples:")
    for i in range(1, min(len(y)+1, 4)):
        print(f'┌X: "{X[-i]}"')
        print(f'└y: "{y[-i]}"')
    print()

    if type(X) is list:
        X = tuple(X)
        y = tuple(y)

    return tokenize_inputs(tokenizer, X, y)

In [31]:
def batch_detokenize(tokenizer, tokens):
    tokens = np.where(tokens != -100, tokens, tokenizer.pad_token_id) # Replace -100 in the labels as we can't decode them
    texts = tokenizer.batch_decode(tokens, skip_special_tokens=True)

    for i in range(len(texts)):
        text = texts[i].strip()
        texts[i] = text

    return texts

In [32]:
print(tokenize_and_show_inputs(tokenizer, [""], [""]))
print()
print(tokenize_and_show_inputs(tokenizer, ["Holding out for a hero"], ["hero"]))

Pretokenized examples:
┌X: ""
└y: ""

{'input_ids': [[1]], 'attention_mask': [[1]], 'labels': [[1]]}


Pretokenized examples:
┌X: "Holding out for a hero"
└y: "hero"

{'input_ids': [[8470, 53, 91, 21, 3, 9, 160, 32, 1]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1]], 'labels': [[160, 32, 1]]}

In [33]:
# Create torch dataset

class Dataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels=None):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        if self.labels:
            item["labels"] = torch.tensor(self.labels[idx]) # torch.tensor(self.labels[idx], dtype=torch.float)
        return item

    def __len__(self):
        return len(self.encodings["input_ids"])

def get_dataset(Xy_tokenized):
    dataset = Dataset(Xy_tokenized)
    return dataset

In [34]:
# DataCollator

data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=MODEL_NAME)

In [35]:
# DataLoader
from torch.utils.data import DataLoader

def get_dataloader(dataset, batch_size):
    dataloader = DataLoader(
        dataset, batch_size=batch_size, collate_fn=data_collator
    )
    return dataloader

# Metrics and Training Arguments

In [36]:
X_eval, y_eval = X_val, y_val

In [37]:
def merge_samples(X, Y):
    merged_samples = {}
    for x, y in zip(X, Y):
        if x not in merged_samples:
            merged_samples[x] = set()
        merged_samples[x].add(y)
    merged_y = [list(merged_samples[x]) for x in X]
    return merged_y

In [38]:
# Remove duplicate samples after merging their outputs

def squeeze_samples(X, candidates, referenceses):
    squeezed_candidates_dict = {}
    squeezed_referenceses_dict = {}
    for i in range(len(X)):
        x = X[i]
        if x not in squeezed_candidates_dict:
            squeezed_candidates_dict[x] = candidates[i]
            squeezed_referenceses_dict[x] = referenceses[i]
    squeezed_X = list(squeezed_candidates_dict.keys())
    squeezed_candidates = list(squeezed_candidates_dict.values())
    squeezed_referenceses_dict = list(squeezed_referenceses_dict.values())
    return squeezed_X, squeezed_candidates, squeezed_referenceses_dict

## Classification Metrics

In [39]:
# " One | Two | Three " => ["One", "Two", "Three"]
def split_and_clean(text, separator=' '):
    return [part_of_text.strip() for part_of_text in text.strip().split(separator)]

In [40]:
def apply_on_vec_mpqa(vec, t_id=None, p_id=None, i_id=None, t_ids=None, p_ids=None, i_ids=None):
    t_index = None

    if t_id:
        t_ids = [t_id]
    if t_ids:
        for t_id in t_ids:
            if t_id in type_classid2classname:
                t_index = type_classid2classindex[t_id]
                vec[t_index] = 1

    if p_id:
        p_ids = [p_id]
    if p_ids:
        p_startpos = 0
        for p_id in p_ids:
            if p_id in polarity_classid2classname:
                p_index = polarity_classid2classindex[p_id]
                vec[p_startpos + p_index] = 1

    if i_id:
        i_ids = [i_id]
    if i_ids:
        i_startpos = 0
        for i_id in i_ids:
            if i_id in intensity_classid2classname:
                i_indices = intensity_classid2classindices[i_id]
                for i_index in i_indices:
                    vec[i_startpos + i_index] = 1

    return vec

In [41]:
def apply_on_vec_emotion(vec, emotion_id=None, emotion_ids=None):
    if emotion_id:
        emotion_ids = [emotion_id]
    if emotion_ids:
        for emotion_id in emotion_ids:
            if emotion_id in emotion_classid2classname:
                emotion_index = emotion_classid2classindex[emotion_id]
                vec[emotion_index] = 1

    return vec

In [42]:
def apply_on_vec_agnews(vec, id=None, ids=None):
    if id:
        ids = [id]
    if ids:
        startpos = 0
        for id in ids:
            if id in agnews_classid2classname:
                index = agnews_classid2classindex[id]
                vec[startpos + index] = 1
    return vec

In [43]:
def apply_on_vec_amzn(vec, id=None, ids=None):
    if id:
        ids = [id]
    if ids:
        startpos = 0
        for id in ids:
            if id in amzn_classid2classname:
                index = amzn_classid2classindex[id]
                vec[startpos + index] = 1
    return vec

In [44]:
def outputs_text_to_vec(outputs_text):

    if DATASET_NAME == 'MPQA-T':
        outputs_vec = np.zeros((len(outputs_text), 4), dtype=int) # Empty 5-dimensional vector
        for batch_i in range(len(outputs_text)):
            t_ids = split_and_clean(outputs_text[batch_i], ' ')
            outputs_vec[batch_i] = apply_on_vec_mpqa(outputs_vec[batch_i], t_ids=t_ids)

    elif DATASET_NAME == 'MPQA-P':
        outputs_vec = np.zeros((len(outputs_text), 2), dtype=int) # Empty 3-dimensional vector
        for batch_i in range(len(outputs_text)):
            p_ids = split_and_clean(outputs_text[batch_i], ' ')
            outputs_vec[batch_i] = apply_on_vec_mpqa(outputs_vec[batch_i], p_id=p_ids[0])

    elif DATASET_NAME == 'MPQA-I':
        outputs_vec = np.zeros((len(outputs_text), 3), dtype=int) # Empty 3-dimensional vector
        for batch_i in range(len(outputs_text)):
            i_ids = split_and_clean(outputs_text[batch_i], ' ')
            outputs_vec[batch_i] = apply_on_vec_mpqa(outputs_vec[batch_i], i_ids=i_ids)
    
    elif DATASET_NAME == 'EMOTION':
        outputs_vec = np.zeros((len(outputs_text), 6), dtype=int) # Empty 6-dimensional vector
        for batch_i in range(len(outputs_text)):
            emotion_ids = split_and_clean(outputs_text[batch_i], ' ')
            outputs_vec[batch_i] = apply_on_vec_emotion(outputs_vec[batch_i], emotion_ids=emotion_ids)

    elif DATASET_NAME == 'AGNEWS':
        outputs_vec = np.zeros((len(outputs_text), 4), dtype=int) # Empty 4-dimensional vector
        for batch_i in range(len(outputs_text)):
            ids = split_and_clean(outputs_text[batch_i], ' ')
            outputs_vec[batch_i] = apply_on_vec_agnews(outputs_vec[batch_i], id=ids[0])

    elif DATASET_NAME.startswith('AMZN'):
        outputs_vec = np.zeros((len(outputs_text), 5), dtype=int) # Empty 5-dimensional vector
        for batch_i in range(len(outputs_text)):
            ids = split_and_clean(outputs_text[batch_i], ' ')
            outputs_vec[batch_i] = apply_on_vec_amzn(outputs_vec[batch_i], id=ids[0])

    return outputs_vec

### MPQA Type Metrics

In [45]:
def calculate_type_metrics(preds, targets, decimals=6):
    targets = targets[:, :NUM_TYPE_CLASSES]
    preds   = preds[:, :NUM_TYPE_CLASSES]

    accuracy_list = np.sum(preds == targets, axis=0).astype(float) / preds.shape[0]
    f1_list = f1_score(y_true=targets, y_pred=preds, zero_division=0, average=None)
    precision_list = precision_score(y_true=targets, y_pred=preds, zero_division=0, average=None)
    recall_list = recall_score(y_true=targets, y_pred=preds, zero_division=0, average=None)

    TP = np.sum(preds & targets)
    FP = np.sum(preds & (1-targets))
    FN = np.sum((1-preds) & targets)

    if TP + FP > 0:
        micro_precision = TP / (TP + FP)
    else:
        micro_precision = 1

    if TP + FN > 0:
        micro_recall = TP / (TP + FN)
    else:
        micro_recall = 1

    micro_f1 = statistics.harmonic_mean([micro_precision, micro_recall])
    micro_accuracy = np.mean(preds == targets)

    # macro_precision = np.mean(precision_list)
    # macro_recall = np.mean(recall_list)
    # macro_f1 = statistics.harmonic_mean([macro_precision, macro_recall])
    # macro_accuracy = np.mean(accuracy_list)

    # hamming_loss = np.mean(preds != targets) # The fraction of labels that are incorrectly predicted
    exact_match_ratio = np.mean(np.sum(preds == targets, axis = 1) == NUM_TYPE_CLASSES) # The percentage of samples that have all their labels classified correctly

    return {
        'type_exact_match_ratio': np.round(exact_match_ratio, decimals),
        'type_micro_f1': np.round(micro_f1, decimals),
        'type_micro_precision': np.round(micro_precision, decimals),
        'type_micro_recall': np.round(micro_recall, decimals),
        'type_micro_accuracy': np.round(np.mean(micro_accuracy), decimals),
        # 'type_hamming': np.round(hamming_loss, decimals),
        # 'type_macro_f1': np.round(macro_f1, decimals),
        # 'type_macro_precision': np.round(macro_precision, decimals),
        # 'type_macro_recall': np.round(macro_recall, decimals),
        # 'type_macro_accuracy': np.round(macro_accuracy, decimals),
        'type_f1': np.round(f1_list, decimals).tolist(),
        'type_precision': np.round(precision_list, decimals).tolist(),
        'type_recall': np.round(recall_list, decimals).tolist(),
        'type_accuracy': np.round(accuracy_list, decimals).tolist(),
    }

### MPQA Polarity Metrics

In [46]:
def calculate_polarity_f1_measure(extracted_polarity_preds, extracted_polarity_targets):
    extracted_polarity_targets = np.argmax(extracted_polarity_targets, axis=-1)
    extracted_polarity_preds   = np.argmax(extracted_polarity_preds,   axis=-1)
    polarity_weighted_f1 = f1_score(extracted_polarity_targets, extracted_polarity_preds, average='weighted')
    return polarity_weighted_f1

In [47]:
def calculate_polarity_correctness_score(extracted_polarity_preds, extracted_polarity_targets):
    extracted_polarity_targets = np.argmax(extracted_polarity_targets, axis=-1)
    extracted_polarity_preds   = np.argmax(extracted_polarity_preds,   axis=-1)
    polarity_score = np.sum(extracted_polarity_preds == extracted_polarity_targets)
    return polarity_score

In [48]:
def calculate_polarity_metrics(preds, targets, decimals=6):
    batch_size = len(preds)

    extracted_polarity_targets = targets
    extracted_polarity_preds   = preds

    number_of_samples = batch_size

    polarity_acc = calculate_polarity_correctness_score(extracted_polarity_preds, extracted_polarity_targets) / number_of_samples
    polarity_weighted_f1 = calculate_polarity_f1_measure(extracted_polarity_preds, extracted_polarity_targets)

    return {
        'polarity_accuracy': np.round(polarity_acc, decimals),
        'polarity_weighted_f1': np.round(polarity_weighted_f1, decimals),
    }

### MPQA Intensity Metrics

In [49]:
# Convert 3-dim intensity vector to its corresponding number

def get_intensity_id(vec):
    vec = vec.tolist()
    if vec == [1, 0, 0]:
        return 0
    if vec == [1, 1, 0]:
        return 1
    if vec == [0, 1, 0]:
        return 2
    if vec == [0, 1, 1]:
        return 3
    if vec == [0, 0, 1]:
        return 4
    return 1 # everything is equal to low-medium by default

In [50]:
def calculate_intensity_d_correctness_score(extracted_intensity_preds, extracted_intensity_targets, d=1):
    batch_size = len(extracted_intensity_preds)
    intensity_score = 0
    for i in range(batch_size):
        target_id = get_intensity_id(extracted_intensity_targets[i]) # everything is equal to low-medium by default
        pred_id   = get_intensity_id(extracted_intensity_preds[i])   # everything is equal to low-medium by default
        if abs(target_id - pred_id) <= d:
            intensity_score += 1
    return intensity_score

In [51]:
def calculate_intensity_custom_weighted_f1_measure(extracted_intensity_preds, extracted_intensity_targets):

    whole = 1.0
    with_penalty = 0
    half_false = 1
    thresh = 0.5
    trues = {'medium': 0, 'medium-high': 0, 'low': 0, 'high': 0, 'low-medium': 0}  # TP
    cnt = {'medium': 0, 'medium-high': 0, 'low': 0, 'high': 0, 'low-medium': 0}    # TP + FN
    falses = {'medium': 0, 'medium-high': 0, 'low': 0, 'high': 0, 'low-medium': 0} # FP

    preds_indices = np.argmax(extracted_intensity_preds, axis=-1)

    for i in range(len(preds_indices)):

        if preds_indices[i] == 0:
            if extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 0 and  extracted_intensity_targets[i][2] == 1:
                falses['low'] += 1
            if extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 0:
                falses['low'] += half_false
            if extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 1:
                falses['low'] += half_false

        if preds_indices[i] == 1:
            if extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 0 and  extracted_intensity_targets[i][2] == 1:
                falses['medium'] += half_false
            if extracted_intensity_targets[i][0] == 1 and  extracted_intensity_targets[i][1] == 0 and  extracted_intensity_targets[i][2] == 0:
                falses['medium'] += half_false

        if preds_indices[i] == 2:
            if extracted_intensity_targets[i][0] == 1 and  extracted_intensity_targets[i][1] == 0 and  extracted_intensity_targets[i][2] == 0:
                falses['high'] += 1
            if extracted_intensity_targets[i][0] == 1 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 0:
                falses['high'] += 1
            if extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 1:
                falses['high'] += half_false
            if extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 0:
                falses['high'] += half_false

        if extracted_intensity_targets[i][0] == 1 and  extracted_intensity_targets[i][1] == 0 and  extracted_intensity_targets[i][2] == 0:
            cnt['low'] += 1
            if preds_indices[i] == 0:
                trues['low'] += whole

        elif extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 0:
            cnt['medium'] += 1
            if preds_indices[i] == 1:
                trues['medium'] += whole
            else:
                trues['medium'] += with_penalty

        elif extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 0 and  extracted_intensity_targets[i][2] == 1:
            cnt['high'] += 1
            if preds_indices[i] == 2:
                trues['high'] += whole

        elif extracted_intensity_targets[i][0] == 1 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 0:
            cnt['low-medium'] += 1
            if preds_indices[i] == 0 or preds_indices[i] == 1:
                trues['low-medium'] += whole

        elif extracted_intensity_targets[i][0] == 0 and  extracted_intensity_targets[i][1] == 1 and  extracted_intensity_targets[i][2] == 1:
            cnt['medium-high'] += 1
            if preds_indices[i] == 1 or preds_indices[i] == 2:
                trues['medium-high'] += whole

    weighted_f1 = 0
    weights = 0
    for intensity_class in trues.keys():
        try:
            intensity_class_precision = trues[intensity_class] / (trues[intensity_class] + falses[intensity_class])
        except:
            intensity_class_precision = 1
        try:
            intensity_class_recall = trues[intensity_class] / cnt[intensity_class]
        except:
            intensity_class_recall = 1
        intensity_class_f1 = statistics.harmonic_mean([intensity_class_precision, intensity_class_recall])
        weighted_f1 += intensity_class_f1 * cnt[intensity_class]
        weights += cnt[intensity_class]
    custom_intensity_weighted_f1 = weighted_f1 / weights

    return custom_intensity_weighted_f1

In [52]:
def calculate_intensity_custom_correctness_score(extracted_intensity_preds, extracted_intensity_targets):
    extracted_intensity_preds_argmax = np.argmax(extracted_intensity_preds, axis=-1)
    intensity_custom_score = 0
    for i in range(len(extracted_intensity_preds_argmax)):
        if (extracted_intensity_targets[i, extracted_intensity_preds_argmax[i]] == 1):
            intensity_custom_score += 1
    return intensity_custom_score

In [53]:
def calculate_intensity_metrics(preds, targets, decimals=6):
    batch_size = len(preds)

    extracted_intensity_targets = targets
    extracted_intensity_preds = preds

    number_of_samples = batch_size

    intensity_acc    = calculate_intensity_d_correctness_score(extracted_intensity_preds, extracted_intensity_targets, d=0) / number_of_samples
    intensity_d1_acc = calculate_intensity_d_correctness_score(extracted_intensity_preds, extracted_intensity_targets, d=1) / number_of_samples
    intensity_d2_acc = calculate_intensity_d_correctness_score(extracted_intensity_preds, extracted_intensity_targets, d=2) / number_of_samples
    intensity_d3_acc = calculate_intensity_d_correctness_score(extracted_intensity_preds, extracted_intensity_targets, d=3) / number_of_samples
    intensity_d4_acc = calculate_intensity_d_correctness_score(extracted_intensity_preds, extracted_intensity_targets, d=4) / number_of_samples
    intensity_custom_acc = calculate_intensity_custom_correctness_score(extracted_intensity_preds, extracted_intensity_targets) / number_of_samples
    intensity_custom_weighted_f1 = calculate_intensity_custom_weighted_f1_measure(extracted_intensity_preds, extracted_intensity_targets)

    return {
        'intensity_accuracy': np.round(intensity_acc, decimals),
        'intensity_d1_accuracy': np.round(intensity_d1_acc, decimals),
        'intensity_d2_accuracy': np.round(intensity_d2_acc, decimals),
        'intensity_d3_accuracy': np.round(intensity_d3_acc, decimals),
        'intensity_d4_accuracy': np.round(intensity_d4_acc, decimals),
        'intensity_custom_accuracy': np.round(intensity_custom_acc, decimals),
        'intensity_custom_weighted_f1': np.round(intensity_custom_weighted_f1, decimals),
    }

### EMOTION Metrics

In [54]:
# calculate metrics for EMOTION dataset
def calculate_emotion_f1_measure(extracted_emotion_preds, extracted_emotion_targets, average='weighted'):
    extracted_emotion_targets = np.argmax(extracted_emotion_targets, axis=-1)
    extracted_emotion_preds   = np.argmax(extracted_emotion_preds, axis=-1)
    emotion_f1 = f1_score(extracted_emotion_targets, extracted_emotion_preds, average=average)
    return emotion_f1

def calculate_emotion_correctness_score(extracted_emotion_preds, extracted_emotion_targets):
    extracted_emotion_targets = np.argmax(extracted_emotion_targets, axis=-1)
    extracted_emotion_preds   = np.argmax(extracted_emotion_preds, axis=-1)
    emotion_score = np.sum(extracted_emotion_preds == extracted_emotion_targets)
    return emotion_score

def calculate_emotion_metrics(preds, targets, decimals=6):
    batch_size = len(preds)

    extracted_emotion_targets = targets
    extracted_emotion_preds   = preds

    number_of_samples = batch_size

    acc = calculate_emotion_correctness_score(extracted_emotion_preds, extracted_emotion_targets) / number_of_samples
    weighted_f1 = calculate_emotion_f1_measure(extracted_emotion_preds, extracted_emotion_targets, average='weighted')
    macro_f1 = calculate_emotion_f1_measure(extracted_emotion_preds, extracted_emotion_targets, average='macro')


    return {
        'emotion_accuracy': np.round(acc, decimals),
        'emotion_weighted_f1': np.round(weighted_f1, decimals),
        'emotion_macro_f1': np.round(macro_f1, decimals),
    }

### AG News Metrics

In [55]:
def calculate_agnews_f1_measure(extracted_preds, extracted_targets, average='weighted'):
    extracted_targets = np.argmax(extracted_targets, axis=-1)
    extracted_preds   = np.argmax(extracted_preds,   axis=-1)
    weighted_f1 = f1_score(extracted_targets, extracted_preds, average=average)
    return weighted_f1

In [56]:
def calculate_agnews_correctness_score(extracted_preds, extracted_targets):
    extracted_targets = np.argmax(extracted_targets, axis=-1)
    extracted_preds   = np.argmax(extracted_preds,   axis=-1)
    score = np.sum(extracted_preds == extracted_targets)
    return score

In [57]:
def calculate_agnews_metrics(preds, targets, decimals=6):
    batch_size = len(preds)

    extracted_targets = targets
    extracted_preds   = preds

    number_of_samples = batch_size

    acc = calculate_agnews_correctness_score(extracted_preds, extracted_targets) / number_of_samples
    weighted_f1 = calculate_agnews_f1_measure(extracted_preds, extracted_targets, average='weighted')
    macro_f1 = calculate_agnews_f1_measure(extracted_preds, extracted_targets, average='macro')

    return {
        'agnews_accuracy': np.round(acc, decimals),
        'agnews_weighted_f1': np.round(weighted_f1, decimals),
        'agnews_macro_f1': np.round(macro_f1, decimals),
    }

### Amazon Metrics

In [58]:
def calculate_amzn_f1_measure(extracted_preds, extracted_targets, average='weighted'):
    extracted_targets = np.argmax(extracted_targets, axis=-1)
    extracted_preds   = np.argmax(extracted_preds,   axis=-1)
    weighted_f1 = f1_score(extracted_targets, extracted_preds, average=average)
    return weighted_f1

In [59]:
def calculate_amzn_correctness_score(extracted_preds, extracted_targets):
    extracted_targets = np.argmax(extracted_targets, axis=-1)
    extracted_preds   = np.argmax(extracted_preds,   axis=-1)
    score = np.sum(extracted_preds == extracted_targets)
    return score

In [60]:
def calculate_amzn_metrics(preds, targets, decimals=6):
    batch_size = len(preds)

    extracted_targets = targets
    extracted_preds   = preds

    number_of_samples = batch_size

    acc = calculate_amzn_correctness_score(extracted_preds, extracted_targets) / number_of_samples
    weighted_f1 = calculate_amzn_f1_measure(extracted_preds, extracted_targets, average='weighted')
    macro_f1 = calculate_amzn_f1_measure(extracted_preds, extracted_targets, average='macro')

    return {
        'amzn_accuracy': np.round(acc, decimals),
        'amzn_weighted_f1': np.round(weighted_f1, decimals),
        'amzn_macro_f1': np.round(macro_f1, decimals),
    }

## Metrics

In [61]:
def calculate_metrics(pred):
    targets = np.array(pred.label_ids, dtype=int)
    targets = batch_detokenize(tokenizer, targets)

    preds   = pred.predictions
    preds   = batch_detokenize(tokenizer, preds)

    candidates = preds
    # unmerged_referenceses = [[target] for target in targets]
    referenceses = merge_samples(X_eval, targets)

    metrics = {}

    if DATASET_NAME.startswith('MPQA'):
        targets = outputs_text_to_vec(targets)
        preds   = outputs_text_to_vec(preds)

        if DATASET_NAME == 'MPQA-T':
            metrics.update(calculate_type_metrics(preds, targets))
            metrics['main_metric'] = metrics['type_micro_f1']

        elif DATASET_NAME == 'MPQA-P':
            metrics.update(calculate_polarity_metrics(preds, targets))
            metrics['main_metric'] = metrics['polarity_accuracy']

        elif DATASET_NAME == 'MPQA-I':
            metrics.update(calculate_intensity_metrics(preds, targets))
            metrics['main_metric'] = metrics['intensity_accuracy']
    elif DATASET_NAME == 'EMOTION':
        targets = outputs_text_to_vec(targets)
        preds   = outputs_text_to_vec(preds)
        metrics.update(calculate_emotion_metrics(preds, targets))
        metrics['main_metric'] = metrics['emotion_accuracy']
    elif DATASET_NAME == 'AGNEWS':
        targets = outputs_text_to_vec(targets)
        preds   = outputs_text_to_vec(preds)
        metrics.update(calculate_agnews_metrics(preds, targets))
        metrics['main_metric'] = metrics['agnews_accuracy']

    elif DATASET_NAME.startswith('AMZN'):
        targets = outputs_text_to_vec(targets)
        preds   = outputs_text_to_vec(preds)
        metrics.update(calculate_amzn_metrics(preds, targets))
        metrics['main_metric'] = metrics['amzn_accuracy']

    if X_eval == X_val:
        print('┌X:          ', X_eval[0])
        print('├Candidate:  ', candidates[0])
        print('└References: ', referenceses[0])
        print('┌X:          ', X_eval[-1])
        print('├Candidate:  ', candidates[-1])
        print('└References: ', referenceses[-1])
        print('--- Next Epoch ---')

    return metrics

# Training Setup

In [62]:
# Training Arguments

def get_training_args(fold_counter, seed_counter):
    training_args = Seq2SeqTrainingArguments(
        output_dir = f'models/{EXPERIMENT_NAME}_{fold_counter}_{seed_counter}',
        overwrite_output_dir = True,
        per_device_train_batch_size = PER_DEVICE_TRAIN_BATCH_SIZE,
        per_device_eval_batch_size = PER_DEVICE_VAL_BATCH_SIZE,
        local_rank = LOCAL_RANK,
        fp16 = FP16,
        fp16_opt_level = FP16_OPT_LEVEL,
        fp16_full_eval = FP16_FULL_EVAL,
        logging_strategy = LOGGING_STRATEGY,
        evaluation_strategy = EVAL_STRATEGY,
        save_strategy = SAVE_STRATEGY,
        save_total_limit = 1,
        num_train_epochs = NUM_TRAIN_EPOCHS,
        load_best_model_at_end = LOAD_BEST_MODEL_AT_END,
        metric_for_best_model = METRIC_FOR_BEST_MODEL,
        dataloader_num_workers = NUM_WORKERS,
        seed = SEED,
        group_by_length = True,
        predict_with_generate = PREDICT_WITH_GENERATE,
        report_to = "none",
        full_determinism = True
    )
    print("Number of GPUs:", training_args.n_gpu)
    print("Parallel Mode:", training_args.parallel_mode)
    print()
    return training_args

In [63]:
def free_gpu():
    try: # Delete the "model" after moving it to CPU, if it exists.
        model
    except NameError:
        None
    else:
        model.cpu()
        del model

    with torch.no_grad():
        gc.collect()
        torch.cuda.empty_cache()

In [64]:
# Setup trainer

def setup_trainer(model, train_dataset, val_dataset, optimizer, fold_counter, seed_counter):
    training_args = get_training_args(fold_counter, seed_counter)
    trainer = Seq2SeqTrainer(
        model = model,
        args = training_args,
        optimizers = (optimizer, None),
        train_dataset = train_dataset,
        eval_dataset = val_dataset,
        data_collator = data_collator,
        compute_metrics = calculate_metrics,
        callbacks = CALLBACKS
    )
    return trainer

# Embedding

In [65]:
def get_embedding_bart_encoder(X, y, model):
    if model == None:
        free_gpu()
        model = load_model('facebook/bart-base')
        model = model.to(device)

    Xy_tokenized = tokenize_inputs(emb_tokenizer, tuple(X), tuple(y))
    dataset = get_dataset(Xy_tokenized)
    dataloader = get_dataloader(dataset, PER_DEVICE_VAL_BATCH_SIZE_EMBEDDING)

    encoder = []
    for batch in dataloader:
        gpu_batch = {k:v.to(device) for k,v in batch.items() if k != 'labels'}
        output = model(**gpu_batch)

        # print(output.logits.size())                    # torch.Size([16, maxlen, 50265])
        # print(output.encoder_last_hidden_state.size()) # torch.Size([16, maxlen, 768])

        batch_encoder = torch.reshape(
            torch.sum(output.encoder_last_hidden_state, 1) / torch.sum(torch.reshape(gpu_batch['attention_mask'], (len(batch['attention_mask']), -1, 1)).expand(output.encoder_last_hidden_state.size()), 1)
        , (len(batch['attention_mask']), -1)).to('cpu').detach().numpy()

        encoder.append(batch_encoder)

        del gpu_batch

    model.cpu()
    del model
    free_gpu()

    encoder = np.concatenate(encoder, axis=0)

    return encoder

In [66]:
def get_embedding_bart_scores(X, y, model, get_encoder=False):
    if model is None:
        raise Exception(f"`model` is not defined.")

    Xy_tokenized = tokenize_inputs(emb_tokenizer, tuple(X), tuple(y))
    dataset = get_dataset(Xy_tokenized)
    dataloader = get_dataloader(dataset, PER_DEVICE_VAL_BATCH_SIZE_EMBEDDING)

    scores = [] # (len(X), NUM_CLASSES)
    encoder = [] # List to store encoder's last hidden states

    for batch in dataloader:
        gpu_batch = {k: v.to(device) for k, v in batch.items() if k != "labels"}

        # Forward pass through the model
        outputs = model(**gpu_batch, output_hidden_states=get_encoder, return_dict=True)

        if get_encoder:
            encoder.append(
                torch.reshape(
                    torch.sum(outputs.encoder_hidden_states[-1], 1) /
                    torch.sum(
                        torch.reshape(
                            gpu_batch["attention_mask"],
                            (len(batch["attention_mask"]), -1, 1)
                        ).expand(outputs.encoder_hidden_states[-1].size()),
                        1
                    ),
                    (len(batch["attention_mask"]), -1)
                ).to("cpu").detach().numpy()
            )

        logits = outputs.logits # (batch_size, seq_len, vocab_size)
        logits = logits.cpu().detach().numpy()
        sequences = np.argmax(logits, axis=-1) # (batch_size, seq_len)

        batch_scores = np.zeros((logits.shape[0], logits.shape[1], NUM_CLASSES)) # (batch_size, seq_len, NUM_CLASSES)
        for seq_tokens_i in range(1, logits.shape[1] - 1):
            for class_token_i, class_token in enumerate(CLASSES_TOKENS):
                batch_scores[:, seq_tokens_i, class_token_i] = logits[:, seq_tokens_i, class_token]
            for batch_i in range(logits.shape[0]): # Softmax over class tokens for valid predictions
                if sequences[batch_i, seq_tokens_i] in CLASSES_TOKENS:
                    batch_scores[batch_i, seq_tokens_i] = softmax(batch_scores[batch_i, seq_tokens_i], axis=-1)
                else:
                    batch_scores[batch_i, seq_tokens_i] = 0
        batch_scores = np.max(batch_scores, axis=1).reshape(-1, NUM_CLASSES) # Reduce seq_len dimension

        scores.append(batch_scores)

        del gpu_batch

    # Convert scores and encoder hidden states to single arrays
    scores = np.concatenate(scores, axis=0)
    encoder = np.concatenate(encoder, axis=0) if get_encoder else None

    if get_encoder:
        return scores, encoder
    else:
        return scores

In [67]:
def get_embedding_t5_encoder(X, y, model=None, flan=False, prefix=None):
    if model == None:
        free_gpu()
        embedding_model_name = 't5-base' if flan == False else 'google/flan-t5-base'
        model = load_model(embedding_model_name)
        model = model.to(device)

    X_with_prefix = X
    if prefix is not None:
        X_with_prefix = [prefix+x for x in X]

    Xy_tokenized = tokenize_inputs(emb_tokenizer, tuple(X_with_prefix), tuple(y))
    dataset = get_dataset(Xy_tokenized)
    dataloader = get_dataloader(dataset, PER_DEVICE_VAL_BATCH_SIZE_EMBEDDING)

    encoder = []
    for batch in dataloader:
        gpu_batch = {k:v.to(device) for k,v in batch.items() if k != 'labels'}
        output = model.encoder(**gpu_batch, return_dict=True)

        # print(output.last_hidden_state.size()) # torch.Size([16, maxlen, 768])

        batch_encoder = torch.reshape(
            torch.sum(output.last_hidden_state, 1) / torch.sum(torch.reshape(gpu_batch['attention_mask'], (len(batch['attention_mask']), -1, 1)).expand(output.last_hidden_state.size()), 1)
        , (len(batch['attention_mask']), -1)).to('cpu').detach().numpy()

        encoder.append(batch_encoder)

        del gpu_batch

    model.cpu()
    del model
    free_gpu()

    encoder = np.concatenate(encoder, axis=0)

    return encoder

In [68]:
def get_embedding_t5_scores(X, y, model, get_encoder=False):
    if model is None:
        raise Exception(f'`model` is not defined.')

    Xy_tokenized = tokenize_inputs(tokenizer, tuple(X), tuple(y))
    dataset = get_dataset(Xy_tokenized)
    dataloader = get_dataloader(dataset, PER_DEVICE_VAL_BATCH_SIZE_EMBEDDING)

    scores = []  # (len(X), NUM_CLASSES)
    encoder = []  # List to store the encoder's last hidden states

    for batch in dataloader:
        gpu_batch = {k: v.to(device) for k, v in batch.items() if k != 'labels'}

        output = model.generate(**gpu_batch, return_dict_in_generate=True, output_scores=True, max_new_tokens=MAX_NEW_TOKENS, renormalize_logits=True, output_hidden_states=get_encoder)

        if get_encoder:
            encoder.append(
                torch.reshape(
                    torch.sum(output.encoder_hidden_states[-1], 1) /
                    torch.sum(
                        torch.reshape(
                            gpu_batch["attention_mask"],
                            (len(batch["attention_mask"]), -1, 1)
                        ).expand(output.encoder_hidden_states[-1].size()),
                        1
                    ),
                    (len(batch["attention_mask"]), -1)
                ).to("cpu").detach().numpy()
            )

        outputsequences = output.sequences.cpu().detach().numpy()
        outputscores = np.array([score.cpu().detach().numpy() for score in output.scores])
        outputscores = outputscores.transpose([1, 0, 2]) # (batch_size, seq_len, vocab_size)

        batch_scores = np.zeros((outputscores.shape[0], outputscores.shape[1], NUM_CLASSES)) # (batch_size, seq_len, NUM_CLASSES)
        for seq_tokens_i in range(outputscores.shape[1]-1):
            for class_token_i, class_token in enumerate(CLASSES_TOKENS):
                batch_scores[:, seq_tokens_i, class_token_i] = outputscores[:, seq_tokens_i, class_token]
            for batch_i in range(outputscores.shape[0]): # Ignore non class tokens, and softmax over class tokens
                if outputsequences[batch_i, seq_tokens_i+1] in CLASSES_TOKENS:
                    batch_scores[batch_i, seq_tokens_i] = softmax(batch_scores[batch_i, seq_tokens_i], axis=-1)
                else:
                    batch_scores[batch_i, seq_tokens_i] = 0
        batch_scores = np.max(batch_scores, axis=1).reshape(-1, NUM_CLASSES) # (batch_size, NUM_CLASSES) # This is especially important for multi-label tasks

        scores.append(batch_scores)

        del gpu_batch

    # Convert scores and encoder hidden states to single arrays
    scores = np.concatenate(scores, axis=0)
    encoder = np.concatenate(encoder, axis=0) if get_encoder else None

    if get_encoder:
        return scores, encoder
    else:
        return scores

In [69]:
def get_embedding(X, y, embedding_method=EMBEDDING_METHOD_FIRST_ITERATION, model=None):
    with torch.no_grad():
        if embedding_method == 'BART-ENCODER':
            return get_embedding_bart_encoder(X, y, model)
        elif embedding_method == 'BART-SCORES':
            return get_embedding_bart_scores(X, y, model)
        elif embedding_method == 'BART-SCORES+ENCODER':
            return get_embedding_bart_scores(X, y, model, get_encoder=True)
        elif embedding_method == 'T5-ENCODER':
            return get_embedding_t5_encoder(X, y, model=model, flan=False, prefix=EMBEDDING_PREFIX)
        elif embedding_method == 'FLAN-T5-ENCODER':
            return get_embedding_t5_encoder(X, y, model=model, flan=True, prefix=EMBEDDING_PREFIX)
        elif embedding_method == 'FLAN-T5-SCORES':
            return get_embedding_t5_scores(X, y, model)
        elif embedding_method == 'FLAN-T5-SCORES+ENCODER':
            return get_embedding_t5_scores(X, y, model, get_encoder=True)
        else:
            raise Exception(f"The embedding method `{embedding_method}` is not defined.")

# Sampling

In [70]:
def sample_balanced(X, y, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[0], seed=0):
    seen = [False] * len(X) # Flag used for not including already seen samples twice.
    sampled_X = []
    sampled_y = []
    rest_X    = []
    rest_y    = []

    for class_name in CLASSES:
        partial_X = []
        partial_y = []
        for i, (ax, ay) in enumerate(zip(X, y)):
            if seen[i] == False and class_name in ay: # May include 1+ types in MPQA-T task because of using 'in' keyword instead of '=='.
                seen[i] = True
                partial_X.append(ax)
                partial_y.append(ay)

        sampled_ids = sample_without_replacement(len(partial_X), number_of_samples, random_state=seed)
        for id in range(len(partial_X)):
            if id in sampled_ids:
                sampled_X.append(partial_X[id])
                sampled_y.append(partial_y[id])
            else:
                rest_X.append(partial_X[id])
                rest_y.append(partial_y[id])

    return sampled_X, sampled_y, rest_X, rest_y

In [71]:
def sample_random(X, y, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[0], seed=0):
    sampled_X = []
    sampled_y = []
    rest_X    = []
    rest_y    = []

    sampled_ids = sample_without_replacement(len(X), number_of_samples, random_state=seed)
    for id in range(len(X)):
        if id in sampled_ids:
            sampled_X.append(X[id])
            sampled_y.append(y[id])
        else:
            rest_X.append(X[id])
            rest_y.append(y[id])

    return sampled_X, sampled_y, rest_X, rest_y

In [72]:
def sample_kmeans_random(X, y, emb, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[0], seed=0):
    km = KMeans(n_clusters=number_of_samples, init=KMEANS_INIT, n_init=KMEANS_CENTROID_SEEDS, max_iter=300, random_state=seed, algorithm=KMEANS_ALGORITHM)
    km.fit(emb)
    centers = np.array(km.cluster_centers_)
    cluster_ids, cluster_sizes = np.unique(km.labels_, return_counts=True)
    print(f"Number of elements assigned to each cluster: {cluster_sizes}")

    sampled_X = []
    sampled_y = []
    rest_X = []
    rest_y = []

    for cluster_id in cluster_ids:
        cluster_emb = emb[km.labels_ == cluster_id]
        selected_ids = np.arange(len(emb))[km.labels_ == cluster_id]
        sampled_ids = sample_without_replacement(len(cluster_emb), 1, random_state=seed)
        sampled_id = sampled_ids[0]
        sampled_X.append(X[selected_ids[sampled_id]])
        sampled_y.append(y[selected_ids[sampled_id]])
        for i, id in enumerate(selected_ids):
            if i != sampled_id:
                rest_X.append(X[id])
                rest_y.append(y[id])

    return sampled_X, sampled_y, rest_X, rest_y

In [73]:
def sample_kmeans_representative(X, y, emb, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[0], seed=0):
    km = KMeans(n_clusters=number_of_samples, init=KMEANS_INIT, n_init=KMEANS_CENTROID_SEEDS, max_iter=300, random_state=seed, algorithm=KMEANS_ALGORITHM)
    km.fit(emb)
    centers = np.array(km.cluster_centers_)
    cluster_ids, cluster_sizes = np.unique(km.labels_, return_counts=True)
    print(f"Number of elements assigned to each cluster: {cluster_sizes}")

    sampled_X = []
    sampled_y = []
    rest_X = []
    rest_y = []

    for cluster_id in cluster_ids:
        cluster_emb = emb[km.labels_ == cluster_id]
        selected_ids = np.arange(len(emb))[km.labels_ == cluster_id]
        closests, distances = pairwise_distances_argmin_min(centers[cluster_id:cluster_id+1], cluster_emb)
        closest = closests[0]
        sampled_X.append(X[selected_ids[closest]])
        sampled_y.append(y[selected_ids[closest]])
        for i, id in enumerate(selected_ids):
            if i != closest:
                rest_X.append(X[id])
                rest_y.append(y[id])

    return sampled_X, sampled_y, rest_X, rest_y

In [74]:
def sample_entropy(X, y, emb, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION, seed=0, encoder_emb=None):
    entropies = - np.sum(emb * np.log(emb), axis=1)
    sorted_ids = np.argsort(entropies)
    sampled_ids = sorted_ids[-number_of_samples:]

    sampled_encoder_emb = []
    sampled_X = []
    sampled_y = []
    rest_X = []
    rest_y = []

    for id in range(len(X)):
        if id in sampled_ids:
            if encoder_emb is not None:
                sampled_encoder_emb.append(encoder_emb[id])
            sampled_X.append(X[id])
            sampled_y.append(y[id])
        else:
            rest_X.append(X[id])
            rest_y.append(y[id])

    if encoder_emb is not None:
        return sampled_X, sampled_y, rest_X, rest_y, np.array(sampled_encoder_emb)

    return sampled_X, sampled_y, rest_X, rest_y

In [75]:
def sample_entropy_then_kmeans_representative(X, y, emb, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[0], seed=0):

    if type(emb).__name__ == 'tuple':
        kmeans_emb = emb[1] # Encoder
        entropy_emb = emb[0] # Scores
    else:
        kmeans_emb = emb # Scores
        entropy_emb = emb # Scores

    sampled_X_1, sampled_y_1, rest_X_1, rest_y_1, sampled_encoder_emb = sample_entropy(X, y, entropy_emb, number_of_samples*UNREP_ALPHA, seed, encoder_emb=kmeans_emb)
    sampled_X_2, sampled_y_2, rest_X_2, rest_y_2 = sample_kmeans_representative(sampled_X_1, sampled_y_1, sampled_encoder_emb, number_of_samples, seed)

    sampled_X = sampled_X_2
    sampled_y = sampled_y_2
    rest_X = rest_X_1 + rest_X_2
    rest_y = rest_y_1 + rest_y_2

    return sampled_X, sampled_y, rest_X, rest_y

In [76]:
def sample_kmeans_representative_then_entropy(X, y, emb, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[0], seed=0):

    if type(emb).__name__ == 'tuple':
        kmeans_emb = emb[1] # Encoder
        entropy_emb = emb[0] # Scores
    else:
        kmeans_emb = emb # Scores
        entropy_emb = emb # Scores

    km = KMeans(n_clusters=number_of_samples, init=KMEANS_INIT, n_init=KMEANS_CENTROID_SEEDS, max_iter=300, random_state=seed, algorithm=KMEANS_ALGORITHM)
    km.fit(kmeans_emb)
    centers = np.array(km.cluster_centers_)
    cluster_ids, cluster_sizes = np.unique(km.labels_, return_counts=True)
    print(f"Number of elements assigned to each cluster: {cluster_sizes}")

    sampled_X = []
    sampled_y = []
    rest_X = []
    rest_y = []

    for cluster_id in cluster_ids:

        cluster_entropy_emb = entropy_emb[km.labels_ == cluster_id]
        selected_ids = np.arange(len(entropy_emb))[km.labels_ == cluster_id]
        cluster_X = []
        cluster_y = []
        for id in selected_ids:
            cluster_X.append(X[id])
            cluster_y.append(y[id])

        one_sampled_X, one_sampled_y, rest_cluster_X, rest_cluster_y = sample_entropy(cluster_X, cluster_y, cluster_entropy_emb, 1, seed)

        sampled_X += one_sampled_X
        sampled_y += one_sampled_y
        rest_X += rest_cluster_X
        rest_y += rest_cluster_y

    return sampled_X, sampled_y, rest_X, rest_y

In [77]:
def sample(X, y, emb=None, sampling_method=SAMPLING_METHOD_FIRST_ITERATION, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[0], seed=0):
    if sampling_method == 'BALANCED':
        return sample_balanced(X, y, number_of_samples, seed)
    elif sampling_method == 'RANDOM':
        return sample_random(X, y, number_of_samples, seed)
    elif sampling_method == 'KMEANS_RANDOM':
        return sample_kmeans_random(X, y, emb, number_of_samples, seed)
    elif sampling_method == 'KMEANS_REPRESENTATIVE':
        return sample_kmeans_representative(X, y, emb, number_of_samples, seed)
    elif sampling_method == 'ENTROPY':
        return sample_entropy(X, y, emb, number_of_samples, seed)
    elif sampling_method == 'ENTROPY_THEN_KMEANS_REPRESENTATIVE':
        return sample_entropy_then_kmeans_representative(X, y, emb, number_of_samples, seed)
    elif sampling_method == 'KMEANS_REPRESENTATIVE_THEN_ENTROPY':
        return sample_kmeans_representative_then_entropy(X, y, emb, number_of_samples, seed)
    else:
        raise Exception(f"The sampling method `{sampling_method}` is not defined.")

# Train

In [78]:
%mkdir results

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [79]:
# Train

folds_val_log          = INIT_FOLDS_VAL_LOG
folds_test_log         = INIT_FOLDS_TEST_LOG
preds_texts_val_list   = INIT_PREDS_TEXTS_VAL_LIST
targets_texts_val_list = INIT_TARGETS_TEXTS_VAL_LIST
sampled_list           = INIT_SAMPLED_LIST
duration_log = ''

for fold_counter in range(MAX_FOLDS):
    print(f'\n\033[1mFold {fold_counter}/{MAX_FOLDS-1}:\033[0m')

    for seed_counter in range(SKIP_SAMPLING_SEEDS, REPEAT_SAMPLING):
        print(f'\n\033[1mFold {fold_counter}/{MAX_FOLDS-1} | Seed {seed_counter}/{REPEAT_SAMPLING-1}:\033[0m')

        set_seed()

        folds_val_log[-1].append([])
        folds_test_log[-1].append([])
        preds_texts_val_list[-1].append([])
        sampled_list[-1].append([])

        if seed_counter > 0: # Reset Model
            model.cpu()
            del model
            free_gpu()

        model=None
        (X_train_rest, y_train_rest), (X_val, y_val), (X_test, y_test) = fetch_dataset(dataset_name=DATASET_NAME, fold=fold_counter, show_counter=(seed_counter==0))
        X_train, y_train = [], []

        for sampling_iteration in range(SAMPLING_ITERATIONS):
            print(f'\n\033[1mFold {fold_counter}/{MAX_FOLDS-1} | Seed {seed_counter}/{REPEAT_SAMPLING-1} | Iteration {sampling_iteration}/{SAMPLING_ITERATIONS-1}:\033[0m')
            duration_log += f'Fold {fold_counter}/{MAX_FOLDS-1} | Seed {seed_counter}/{REPEAT_SAMPLING-1} | Iteration {sampling_iteration}/{SAMPLING_ITERATIONS-1}:\n'

            logging.disable(logging.INFO)

            embedding_method = EMBEDDING_METHOD_FIRST_ITERATION if sampling_iteration == 0 or EMBEDDING_METHOD_SECOND_ITERATION_PLUS == "SAME_AS_BEFORE" else EMBEDDING_METHOD_SECOND_ITERATION_PLUS
            sampling_method  = SAMPLING_METHOD_FIRST_ITERATION  if sampling_iteration == 0 or SAMPLING_METHOD_SECOND_ITERATION_PLUS  == "SAME_AS_BEFORE" else SAMPLING_METHOD_SECOND_ITERATION_PLUS

            embedding_start_time = datetime.now()
            if sampling_method in ['RANDOM', 'BALANCED']:
                emb_train = None
            else:
                emb_train = get_embedding(X_train_rest, y_train_rest, embedding_method=embedding_method, model=model)
            duration_log += f'Embedding Time: {datetime.now()-embedding_start_time}\n'

            sampling_start_time = datetime.now()
            X_train_sampled, y_train_sampled, X_train_rest, y_train_rest = sample(X_train_rest, y_train_rest, emb_train, sampling_method=sampling_method, number_of_samples=NUMBER_OF_SAMPLES_PER_ITERATION[sampling_iteration], seed=seed_counter)
            duration_log += f'Sampling Time: {datetime.now()-sampling_start_time}\n'

            if AFL_APPROACH == 'IN-CONTEXT':
                X_train_sampled = [x.splitlines()[-1] for x in X_train_sampled]

                support_set_context_sampled = ''
                for x, y in zip(X_train_sampled, y_train_sampled):
                    support_set_context_sampled += x + ' ' + y + '\n'

                X_train_rest = [support_set_context_sampled + x for x in X_train_rest]
                X_val        = [support_set_context_sampled + x for x in X_val]
                X_test       = [support_set_context_sampled + x for x in X_test]

            sampled_list[-1][-1].append((X_train_sampled, y_train_sampled))

            X_train += X_train_sampled
            y_train += y_train_sampled

            Xy_train_tokenized = tokenize_inputs(tokenizer, tuple(X_train), tuple(y_train)) if seed_counter != 0 else tokenize_and_show_inputs(tokenizer, X_train, y_train)
            Xy_val_tokenized   = tokenize_inputs(tokenizer, tuple(X_val),   tuple(y_val))
            Xy_test_tokenized  = tokenize_inputs(tokenizer, tuple(X_test),  tuple(y_test))

            n_train_samples = len(X_train)
            n_val_samples   = len(X_val)
            n_test_samples  = len(X_test)

            n_samples = n_train_samples + n_val_samples + n_test_samples
            if seed_counter == 0:
                print(f'Train set size:      {n_train_samples} \t({100*n_train_samples/n_samples}%)')
                print(f'Validation set size: {n_val_samples} \t({100*n_val_samples/n_samples}%)')
                print(f'Test set size:       {n_test_samples} \t({100*n_test_samples/n_samples}%)')
                print()

            train_dataset = get_dataset(Xy_train_tokenized)
            val_dataset   = get_dataset(Xy_val_tokenized)
            test_dataset  = get_dataset(Xy_test_tokenized)

            if sampling_iteration == 0 or RESET_MODEL_AFTER_EACH_ITERATION: # Reset Model
                free_gpu()
                model = load_model(MODEL_NAME)
                model = model.to(device)

            optimizer = load_optimizer(model)
            X_eval, y_eval = X_val, y_val
            %mkdir models
            trainer = setup_trainer(model, train_dataset, val_dataset, optimizer, fold_counter, seed_counter)

            if AFL_APPROACH == "FINE-TUNING":
                ft_start_time = datetime.now()
                trainer.train()
                duration_log += f'Fine-Tuning Time: {datetime.now()-sampling_start_time}\n'

            X_eval, y_eval = X_val, y_val
            val_results  = trainer.evaluate(val_dataset)
            X_eval, y_eval = X_test, y_test
            test_results = trainer.evaluate(test_dataset)

            # Best Epochs
            if AFL_APPROACH == "FINE-TUNING":
                if os.path.exists(f'models/{EXPERIMENT_NAME}_{fold_counter}_{seed_counter}'):
                    best_epoch = int(os.listdir(f'models/{EXPERIMENT_NAME}_{fold_counter}_{seed_counter}')[0].split('-')[-1]) * PER_DEVICE_TRAIN_BATCH_SIZE / n_train_samples
                    val_results['best_epoch'] = best_epoch
                    test_results['best_epoch'] = best_epoch
            elif AFL_APPROACH == "IN-CONTEXT":
                val_results['best_epoch'] = 0
                test_results['best_epoch'] = 0
            %rm -r models

            folds_val_log[-1][-1].append(val_results)
            folds_test_log[-1][-1].append(test_results)

            X_eval, y_eval = X_val, y_val
            pred_val = trainer.predict(val_dataset)
            preds_tokens_val = pred_val.predictions
            preds_texts_val = batch_detokenize(tokenizer, preds_tokens_val)
            preds_texts_val_list[-1][-1].append(preds_texts_val)

            logging.disable(logging.NOTSET)

        print("======== CHECKPOINT ========")

        checkpoint = {
            'INIT_FOLDS_VAL_LOG': folds_val_log,
            'INIT_FOLDS_TEST_LOG': folds_test_log,
            'INIT_PREDS_TEXTS_VAL_LIST': preds_texts_val_list,
            'INIT_SAMPLED_LIST': sampled_list
        }

        with open(f'results/{EXPERIMENT_NAME.replace(".ipynb", "")}_checkpoint.json', 'w', encoding ='utf8') as checkpoint_file:
            json.dump(checkpoint, checkpoint_file, ensure_ascii=False, indent=1)

    targets_tokens_val = np.array(pred_val.label_ids, dtype=int)
    targets_texts_val = batch_detokenize(tokenizer, targets_tokens_val)
    targets_texts_val_list.append(targets_texts_val)
    print(f"INIT_TARGETS_TEXTS_VAL_LIST = {targets_texts_val_list},")

    if fold_counter < MAX_FOLDS - 1:
        folds_val_log.append([])
        folds_test_log.append([])
        preds_texts_val_list.append([])
        sampled_list.append([])

Fold 0/0:

Fold 0/0 | Seed 0/4:
Train Labels distribution: {'sadness': 4666, 'anger': 2159, 'love': 1304, 'surprise': 572, 'fear': 1937, 'joy': 5362}
Validation Labels distribution: {'sadness': 550, 'love': 178, 'anger': 275, 'joy': 704, 'fear': 212, 'surprise': 81}
Test Labels distribution: {'sadness': 581, 'joy': 695, 'fear': 224, 'anger': 275, 'love': 159, 'surprise': 66}
Labels distribution: {'sadness': 5797, 'anger': 2709, 'love': 1641, 'surprise': 719, 'fear': 2373, 'joy': 6761}

Fold 0/0 | Seed 0/4 | Iteration 0/0:

Pretokenized examples:
┌X: "i feel safe and accepted"
└y: "joy"
┌X: "i continued to gaze her beauty to feel the depth of her eyes her flawless skin got me vibes her beautiful lips held my heartbeats and her elegance was succeeding in taking away my heart"
└y: "joy"
┌X: "i dun feel blamed"
└y: "sadness"

Train set size:      100 	(2.4390243902439024%)
Validation set size: 2000 	(48.78048780487805%)
Test set size:       2000 	(48.78048780487805%)

Number of trainable parameters in base model: 247577856
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
mkdir: cannot create directory ‘models’: File exists
Number of GPUs: 1
Parallel Mode: ParallelMode.NOT_PARALLEL

/venv/afl-env/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(
You're using a T5TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   cute
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
======== CHECKPOINT ========

Fold 0/0 | Seed 1/4:

Fold 0/0 | Seed 1/4 | Iteration 0/0:
Number of trainable parameters in base model: 247577856
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Number of GPUs: 1
Parallel Mode: ParallelMode.NOT_PARALLEL

/venv/afl-env/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   cute
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
======== CHECKPOINT ========

Fold 0/0 | Seed 2/4:

Fold 0/0 | Seed 2/4 | Iteration 0/0:
Number of trainable parameters in base model: 247577856
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Number of GPUs: 1
Parallel Mode: ParallelMode.NOT_PARALLEL

/venv/afl-env/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   cute
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
======== CHECKPOINT ========

Fold 0/0 | Seed 3/4:

Fold 0/0 | Seed 3/4 | Iteration 0/0:
Number of trainable parameters in base model: 247577856
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Number of GPUs: 1
Parallel Mode: ParallelMode.NOT_PARALLEL

/venv/afl-env/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   cute
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
======== CHECKPOINT ========

Fold 0/0 | Seed 4/4:

Fold 0/0 | Seed 4/4 | Iteration 0/0:
Number of trainable parameters in base model: 247577856
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Number of GPUs: 1
Parallel Mode: ParallelMode.NOT_PARALLEL

/venv/afl-env/lib/python3.10/site-packages/accelerate/accelerator.py:436: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None)
  warnings.warn(

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   cute
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   love
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---

┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
┌X:           im feeling quite sad and sorry for myself but ill snap out of it soon
├Candidate:   sadness
└References:  ['sadness']
┌X:           i feel like i just wanna buy any cute make up i see online or even the one
├Candidate:   joy
└References:  ['joy']
--- Next Epoch ---
======== CHECKPOINT ========
INIT_TARGETS_TEXTS_VAL_LIST = [['sadness', 'sadness', 'love', 'anger', 'joy', 'joy', 'joy', 'joy', 'joy', 'sadness', 'anger', 'joy', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'anger', 'love', 'joy', 'fear', 'sadness', 'joy', 'sadness', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'love', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'anger', 'joy', 'love', 'sadness', 'sadness', 'sadness', 'anger', 'sadness', 'sadness', 'anger', 'love', 'sadness', 'sadness', 'joy', 'joy', 'sadness', 'joy', 'joy', 'anger', 'sadness', 'sadness', 'love', 'love', 'joy', 'sadness', 'joy', 'joy', 'sadness', 'sadness', 'love', 'fear', 'sadness', 'joy', 'joy', 'joy', 'fear', 'love', 'joy', 'sadness', 'anger', 'sadness', 'sadness', 'sadness', 'anger', 'anger', 'sadness', 'anger', 'love', 'joy', 'joy', 'love', 'anger', 'anger', 'joy', 'love', 'anger', 'fear', 'joy', 'anger', 'anger', 'love', 'sadness', 'anger', 'love', 'love', 'sadness', 'joy', 'anger', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'joy', 'sadness', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'anger', 'anger', 'anger', 'joy', 'sadness', 'love', 'fear', 'fear', 'joy', 'sadness', 'fear', 'sadness', 'sadness', 'joy', 'anger', 'sadness', 'fear', 'fear', 'love', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'joy', 'anger', 'surprise', 'love', 'fear', 'love', 'sadness', 'love', 'joy', 'fear', 'anger', 'joy', 'anger', 'joy', 'surprise', 'anger', 'love', 'sadness', 'fear', 'anger', 'joy', 'sadness', 'joy', 'surprise', 'joy', 'fear', 'fear', 'sadness', 'sadness', 'surprise', 'sadness', 'joy', 'fear', 'joy', 'fear', 'sadness', 'love', 'love', 'sadness', 'anger', 'anger', 'joy', 'joy', 'anger', 'anger', 'sadness', 'sadness', 'sadness', 'joy', 'joy', 'joy', 'joy', 'joy', 'joy', 'fear', 'joy', 'fear', 'joy', 'anger', 'sadness', 'fear', 'joy', 'sadness', 'joy', 'anger', 'anger', 'joy', 'fear', 'sadness', 'fear', 'joy', 'joy', 'sadness', 'sadness', 'sadness', 'joy', 'surprise', 'fear', 'sadness', 'sadness', 'joy', 'surprise', 'sadness', 'fear', 'sadness', 'surprise', 'fear', 'joy', 'anger', 'fear', 'joy', 'joy', 'anger', 'surprise', 'joy', 'love', 'joy', 'joy', 'fear', 'joy', 'love', 'fear', 'sadness', 'sadness', 'sadness', 'joy', 'joy', 'surprise', 'anger', 'love', 'joy', 'joy', 'fear', 'joy', 'joy', 'sadness', 'sadness', 'anger', 'joy', 'joy', 'joy', 'joy', 'sadness', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'love', 'sadness', 'joy', 'anger', 'joy', 'joy', 'sadness', 'joy', 'joy', 'joy', 'sadness', 'sadness', 'joy', 'joy', 'sadness', 'joy', 'joy', 'joy', 'fear', 'sadness', 'surprise', 'joy', 'love', 'joy', 'anger', 'sadness', 'joy', 'fear', 'anger', 'fear', 'love', 'love', 'joy', 'fear', 'sadness', 'fear', 'sadness', 'sadness', 'anger', 'sadness', 'fear', 'anger', 'sadness', 'joy', 'sadness', 'love', 'joy', 'joy', 'fear', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'surprise', 'fear', 'anger', 'fear', 'joy', 'joy', 'anger', 'joy', 'love', 'joy', 'anger', 'anger', 'joy', 'joy', 'fear', 'surprise', 'anger', 'sadness', 'sadness', 'fear', 'anger', 'joy', 'sadness', 'anger', 'anger', 'sadness', 'joy', 'love', 'sadness', 'fear', 'sadness', 'sadness', 'joy', 'love', 'joy', 'love', 'anger', 'love', 'joy', 'sadness', 'anger', 'anger', 'joy', 'sadness', 'sadness', 'sadness', 'fear', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'fear', 'love', 'joy', 'sadness', 'anger', 'joy', 'joy', 'joy', 'joy', 'anger', 'sadness', 'sadness', 'sadness', 'joy', 'fear', 'joy', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'joy', 'joy', 'joy', 'joy', 'fear', 'joy', 'joy', 'joy', 'fear', 'joy', 'love', 'fear', 'sadness', 'joy', 'anger', 'sadness', 'fear', 'joy', 'love', 'fear', 'joy', 'joy', 'anger', 'joy', 'joy', 'joy', 'anger', 'joy', 'love', 'joy', 'joy', 'joy', 'anger', 'joy', 'anger', 'joy', 'sadness', 'anger', 'joy', 'anger', 'anger', 'fear', 'sadness', 'anger', 'love', 'fear', 'joy', 'love', 'sadness', 'anger', 'joy', 'love', 'joy', 'anger', 'joy', 'joy', 'anger', 'joy', 'joy', 'joy', 'surprise', 'joy', 'sadness', 'love', 'sadness', 'joy', 'love', 'sadness', 'joy', 'joy', 'joy', 'joy', 'sadness', 'joy', 'anger', 'joy', 'sadness', 'joy', 'sadness', 'love', 'fear', 'love', 'fear', 'anger', 'sadness', 'fear', 'joy', 'fear', 'anger', 'sadness', 'sadness', 'love', 'joy', 'joy', 'joy', 'anger', 'anger', 'joy', 'sadness', 'joy', 'anger', 'sadness', 'surprise', 'love', 'sadness', 'sadness', 'sadness', 'surprise', 'joy', 'sadness', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'surprise', 'love', 'sadness', 'anger', 'joy', 'joy', 'joy', 'joy', 'joy', 'joy', 'joy', 'anger', 'sadness', 'sadness', 'fear', 'anger', 'joy', 'joy', 'sadness', 'fear', 'sadness', 'sadness', 'sadness', 'fear', 'love', 'fear', 'joy', 'sadness', 'sadness', 'anger', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'anger', 'sadness', 'anger', 'sadness', 'sadness', 'love', 'anger', 'love', 'joy', 'joy', 'sadness', 'love', 'fear', 'joy', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'love', 'sadness', 'joy', 'sadness', 'surprise', 'love', 'sadness', 'fear', 'surprise', 'sadness', 'joy', 'love', 'fear', 'love', 'sadness', 'surprise', 'love', 'sadness', 'sadness', 'love', 'fear', 'joy', 'joy', 'fear', 'sadness', 'fear', 'sadness', 'anger', 'sadness', 'sadness', 'sadness', 'anger', 'sadness', 'love', 'sadness', 'joy', 'joy', 'surprise', 'joy', 'sadness', 'sadness', 'joy', 'joy', 'joy', 'anger', 'love', 'joy', 'joy', 'joy', 'joy', 'sadness', 'sadness', 'joy', 'fear', 'anger', 'sadness', 'anger', 'sadness', 'sadness', 'joy', 'joy', 'surprise', 'joy', 'joy', 'joy', 'anger', 'fear', 'sadness', 'joy', 'sadness', 'surprise', 'fear', 'joy', 'fear', 'love', 'anger', 'joy', 'anger', 'joy', 'sadness', 'joy', 'fear', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'joy', 'love', 'sadness', 'sadness', 'love', 'anger', 'love', 'love', 'love', 'joy', 'fear', 'love', 'joy', 'joy', 'joy', 'anger', 'joy', 'love', 'sadness', 'joy', 'joy', 'joy', 'joy', 'joy', 'sadness', 'love', 'joy', 'sadness', 'joy', 'joy', 'fear', 'surprise', 'sadness', 'joy', 'sadness', 'fear', 'sadness', 'fear', 'joy', 'sadness', 'sadness', 'anger', 'sadness', 'joy', 'love', 'anger', 'joy', 'joy', 'sadness', 'joy', 'anger', 'sadness', 'anger', 'joy', 'joy', 'anger', 'anger', 'fear', 'sadness', 'anger', 'joy', 'joy', 'fear', 'joy', 'fear', 'sadness', 'surprise', 'joy', 'joy', 'anger', 'sadness', 'joy', 'fear', 'sadness', 'anger', 'anger', 'joy', 'surprise', 'sadness', 'sadness', 'sadness', 'sadness', 'joy', 'joy', 'surprise', 'joy', 'joy', 'joy', 'anger', 'sadness', 'joy', 'surprise', 'surprise', 'fear', 'joy', 'fear', 'anger', 'joy', 'anger', 'joy', 'anger', 'sadness', 'sadness', 'joy', 'fear', 'sadness', 'joy', 'joy', 'joy', 'sadness', 'joy', 'anger', 'surprise', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'fear', 'joy', 'sadness', 'fear', 'anger', 'sadness', 'joy', 'surprise', 'joy', 'sadness', 'fear', 'sadness', 'joy', 'joy', 'love', 'joy', 'joy', 'sadness', 'sadness', 'joy', 'anger', 'joy', 'sadness', 'joy', 'joy', 'love', 'anger', 'anger', 'joy', 'sadness', 'joy', 'sadness', 'joy', 'anger', 'love', 'anger', 'sadness', 'joy', 'sadness', 'joy', 'joy', 'fear', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'anger', 'sadness', 'fear', 'fear', 'joy', 'joy', 'anger', 'fear', 'joy', 'sadness', 'joy', 'sadness', 'sadness', 'sadness', 'joy', 'joy', 'anger', 'joy', 'joy', 'love', 'joy', 'joy', 'joy', 'joy', 'love', 'sadness', 'anger', 'anger', 'fear', 'fear', 'joy', 'joy', 'joy', 'love', 'joy', 'joy', 'sadness', 'sadness', 'fear', 'sadness', 'fear', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'sadness', 'fear', 'sadness', 'joy', 'joy', 'joy', 'anger', 'joy', 'sadness', 'joy', 'love', 'joy', 'sadness', 'joy', 'anger', 'love', 'love', 'sadness', 'joy', 'anger', 'joy', 'joy', 'fear', 'sadness', 'anger', 'anger', 'joy', 'anger', 'joy', 'joy', 'love', 'joy', 'joy', 'joy', 'sadness', 'sadness', 'joy', 'love', 'sadness', 'joy', 'anger', 'sadness', 'sadness', 'sadness', 'love', 'anger', 'sadness', 'fear', 'sadness', 'joy', 'love', 'sadness', 'joy', 'joy', 'surprise', 'joy', 'joy', 'anger', 'surprise', 'sadness', 'surprise', 'joy', 'joy', 'fear', 'fear', 'joy', 'sadness', 'sadness', 'love', 'joy', 'joy', 'love', 'love', 'fear', 'joy', 'joy', 'joy', 'joy', 'anger', 'joy', 'sadness', 'sadness', 'sadness', 'sadness', 'joy', 'fear', 'anger', 'joy', 'joy', 'joy', 'anger', 'joy', 'joy', 'joy', 'sadness', 'love', 'joy', 'sadness', 'anger', 'love', 'joy', 'love', 'love', 'love', 'joy', 'sadness', 'sadness', 'joy', 'fear', 'sadness', 'anger', 'joy', 'sadness', 'sadness', 'surprise', 'joy', 'love', 'sadness', 'anger', 'sadness', 'sadness', 'love', 'anger', 'fear', 'sadness', 'anger', 'joy', 'fear', 'surprise', 'anger', 'joy', 'surprise', 'sadness', 'love', 'joy', 'sadness', 'joy', 'surprise', 'joy', 'joy', 'joy', 'joy', 'joy', 'anger', 'anger', 'joy', 'sadness', 'fear', 'joy', 'surprise', 'sadness', 'sadness', 'sadness', 'anger', 'anger', 'sadness', 'joy', 'anger', 'sadness', 'joy', 'sadness', 'anger', 'joy', 'love', 'joy', 'sadness', 'sadness', 'anger', 'anger', 'sadness', 'anger', 'sadness', 'joy', 'sadness', 'sadness', 'anger', 'anger', 'joy', 'joy', 'joy', 'anger', 'anger', 'anger', 'joy', 'anger', 'sadness', 'love', 'fear', 'joy', 'love', 'joy', 'joy', 'anger', 'love', 'joy', 'joy', 'joy', 'fear', 'sadness', 'love', 'joy', 'surprise', 'joy', 'sadness', 'anger', 'sadness', 'joy', 'joy', 'anger', 'joy', 'joy', 'anger', 'love', 'love', 'sadness', 'sadness', 'joy', 'sadness', 'joy', 'sadness', 'sadness', 'love', 'joy', 'joy', 'love', 'sadness', 'sadness', 'joy', 'joy', 'joy', 'sadness', 'sadness', 'anger', 'sadness', 'joy', 'fear', 'joy', 'joy', 'sadness', 'joy', 'love', 'sadness', 'sadness', 'anger', 'anger', 'sadness', 'joy', 'joy', 'sadness', 'love', 'surprise', 'fear', 'anger', 'joy', 'surprise', 'sadness', 'anger', 'joy', 'sadness', 'fear', 'joy', 'joy', 'fear', 'love', 'sadness', 'joy', 'fear', 'joy', 'sadness', 'love', 'anger', 'fear', 'fear', 'fear', 'sadness', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'joy', 'sadness', 'love', 'joy', 'joy', 'anger', 'joy', 'fear', 'joy', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'fear', 'joy', 'anger', 'joy', 'joy', 'fear', 'anger', 'sadness', 'surprise', 'sadness', 'joy', 'love', 'fear', 'sadness', 'sadness', 'joy', 'sadness', 'sadness', 'fear', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'joy', 'joy', 'anger', 'joy', 'joy', 'joy', 'joy', 'sadness', 'fear', 'sadness', 'anger', 'joy', 'joy', 'surprise', 'sadness', 'joy', 'anger', 'sadness', 'anger', 'joy', 'anger', 'joy', 'love', 'joy', 'joy', 'joy', 'joy', 'sadness', 'joy', 'anger', 'joy', 'sadness', 'fear', 'joy', 'love', 'joy', 'surprise', 'surprise', 'joy', 'fear', 'joy', 'joy', 'joy', 'sadness', 'fear', 'anger', 'joy', 'anger', 'sadness', 'sadness', 'sadness', 'love', 'anger', 'sadness', 'fear', 'joy', 'joy', 'anger', 'love', 'joy', 'fear', 'joy', 'joy', 'anger', 'sadness', 'fear', 'joy', 'surprise', 'fear', 'sadness', 'joy', 'fear', 'joy', 'sadness', 'sadness', 'fear', 'joy', 'joy', 'sadness', 'sadness', 'sadness', 'joy', 'anger', 'sadness', 'anger', 'love', 'anger', 'joy', 'joy', 'surprise', 'joy', 'anger', 'joy', 'joy', 'anger', 'fear', 'anger', 'anger', 'joy', 'joy', 'anger', 'surprise', 'sadness', 'fear', 'anger', 'joy', 'sadness', 'sadness', 'joy', 'fear', 'sadness', 'surprise', 'anger', 'joy', 'sadness', 'joy', 'love', 'sadness', 'sadness', 'sadness', 'sadness', 'love', 'surprise', 'joy', 'sadness', 'surprise', 'sadness', 'joy', 'fear', 'sadness', 'joy', 'anger', 'sadness', 'sadness', 'joy', 'joy', 'joy', 'joy', 'sadness', 'fear', 'sadness', 'joy', 'love', 'joy', 'anger', 'fear', 'anger', 'joy', 'love', 'sadness', 'anger', 'surprise', 'anger', 'joy', 'anger', 'fear', 'anger', 'sadness', 'sadness', 'fear', 'joy', 'joy', 'joy', 'fear', 'joy', 'sadness', 'joy', 'anger', 'joy', 'anger', 'love', 'sadness', 'joy', 'love', 'fear', 'sadness', 'joy', 'joy', 'joy', 'love', 'surprise', 'sadness', 'anger', 'sadness', 'love', 'sadness', 'fear', 'joy', 'joy', 'anger', 'fear', 'joy', 'joy', 'joy', 'love', 'sadness', 'joy', 'sadness', 'joy', 'anger', 'sadness', 'sadness', 'love', 'sadness', 'joy', 'fear', 'sadness', 'joy', 'joy', 'joy', 'anger', 'anger', 'love', 'joy', 'sadness', 'love', 'fear', 'anger', 'joy', 'joy', 'fear', 'joy', 'fear', 'fear', 'joy', 'joy', 'love', 'fear', 'joy', 'anger', 'joy', 'joy', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'joy', 'love', 'joy', 'sadness', 'joy', 'love', 'sadness', 'joy', 'surprise', 'joy', 'fear', 'joy', 'sadness', 'joy', 'anger', 'joy', 'joy', 'anger', 'joy', 'joy', 'fear', 'love', 'sadness', 'surprise', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'fear', 'sadness', 'sadness', 'love', 'fear', 'anger', 'anger', 'sadness', 'anger', 'sadness', 'anger', 'joy', 'sadness', 'joy', 'anger', 'anger', 'joy', 'joy', 'love', 'anger', 'anger', 'joy', 'joy', 'surprise', 'surprise', 'joy', 'anger', 'sadness', 'joy', 'anger', 'sadness', 'sadness', 'fear', 'joy', 'surprise', 'sadness', 'joy', 'joy', 'anger', 'joy', 'love', 'anger', 'sadness', 'sadness', 'surprise', 'sadness', 'joy', 'sadness', 'love', 'joy', 'joy', 'sadness', 'joy', 'joy', 'joy', 'joy', 'love', 'anger', 'sadness', 'love', 'anger', 'anger', 'surprise', 'sadness', 'joy', 'joy', 'sadness', 'joy', 'joy', 'joy', 'anger', 'joy', 'sadness', 'sadness', 'anger', 'sadness', 'joy', 'fear', 'joy', 'love', 'joy', 'sadness', 'fear', 'love', 'love', 'joy', 'anger', 'joy', 'joy', 'joy', 'joy', 'sadness', 'joy', 'anger', 'love', 'fear', 'sadness', 'sadness', 'sadness', 'joy', 'sadness', 'joy', 'joy', 'love', 'fear', 'sadness', 'joy', 'joy', 'joy', 'joy', 'joy', 'fear', 'anger', 'anger', 'joy', 'sadness', 'joy', 'joy', 'joy', 'love', 'fear', 'sadness', 'anger', 'surprise', 'joy', 'anger', 'sadness', 'anger', 'joy', 'joy', 'joy', 'anger', 'sadness', 'fear', 'fear', 'joy', 'joy', 'fear', 'joy', 'joy', 'fear', 'joy', 'sadness', 'love', 'anger', 'surprise', 'joy', 'fear', 'joy', 'anger', 'anger', 'fear', 'fear', 'joy', 'fear', 'love', 'joy', 'joy', 'anger', 'joy', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'joy', 'anger', 'joy', 'sadness', 'anger', 'sadness', 'fear', 'joy', 'fear', 'joy', 'joy', 'anger', 'joy', 'anger', 'joy', 'sadness', 'sadness', 'fear', 'sadness', 'joy', 'sadness', 'joy', 'love', 'fear', 'joy', 'joy', 'joy', 'joy', 'love', 'joy', 'sadness', 'fear', 'sadness', 'joy', 'love', 'joy', 'sadness', 'anger', 'joy', 'sadness', 'surprise', 'sadness', 'love', 'sadness', 'fear', 'joy', 'joy', 'sadness', 'love', 'anger', 'anger', 'joy', 'fear', 'fear', 'joy', 'joy', 'fear', 'sadness', 'fear', 'anger', 'sadness', 'joy', 'sadness', 'sadness', 'joy', 'fear', 'sadness', 'sadness', 'sadness', 'anger', 'joy', 'sadness', 'anger', 'love', 'sadness', 'fear', 'love', 'fear', 'joy', 'anger', 'joy', 'sadness', 'sadness', 'fear', 'sadness', 'sadness', 'joy', 'surprise', 'sadness', 'sadness', 'surprise', 'sadness', 'joy', 'joy', 'joy', 'joy', 'love', 'sadness', 'sadness', 'joy', 'surprise', 'sadness', 'sadness', 'joy', 'joy', 'anger', 'joy', 'sadness', 'joy', 'joy', 'love', 'love', 'sadness', 'anger', 'fear', 'sadness', 'sadness', 'joy', 'joy', 'fear', 'anger', 'fear', 'fear', 'sadness', 'sadness', 'anger', 'sadness', 'fear', 'anger', 'sadness', 'sadness', 'sadness', 'joy', 'anger', 'surprise', 'sadness', 'sadness', 'sadness', 'joy', 'joy', 'sadness', 'anger', 'sadness', 'sadness', 'anger', 'surprise', 'sadness', 'joy', 'anger', 'fear', 'sadness', 'joy', 'love', 'fear', 'surprise', 'anger', 'joy', 'surprise', 'joy', 'joy', 'sadness', 'surprise', 'fear', 'sadness', 'love', 'sadness', 'joy', 'joy', 'sadness', 'joy', 'fear', 'sadness', 'joy', 'joy', 'joy', 'anger', 'joy', 'love', 'sadness', 'sadness', 'joy', 'anger', 'sadness', 'sadness', 'love', 'fear', 'sadness', 'sadness', 'sadness', 'sadness', 'sadness', 'joy', 'surprise', 'surprise', 'sadness', 'joy', 'anger', 'joy', 'anger', 'joy', 'surprise', 'anger', 'joy', 'joy', 'fear', 'joy', 'sadness', 'joy', 'anger', 'fear', 'sadness', 'sadness', 'fear', 'sadness', 'joy', 'fear', 'joy', 'love', 'sadness', 'anger', 'anger', 'fear', 'joy', 'anger', 'sadness', 'sadness', 'love', 'love', 'sadness', 'anger', 'joy', 'fear', 'joy', 'surprise', 'fear', 'love', 'love', 'sadness', 'joy', 'sadness', 'joy', 'love', 'sadness', 'joy', 'surprise', 'joy', 'joy', 'anger', 'love', 'joy', 'sadness', 'joy', 'fear', 'sadness', 'sadness', 'fear', 'joy', 'fear', 'love', 'joy', 'joy', 'love', 'sadness', 'sadness', 'joy', 'love', 'sadness', 'joy', 'joy', 'fear', 'sadness', 'anger', 'sadness', 'love', 'sadness', 'surprise', 'joy', 'joy', 'sadness', 'sadness', 'joy', 'sadness', 'joy', 'joy', 'joy', 'fear', 'joy', 'fear', 'sadness', 'joy', 'joy', 'sadness', 'sadness', 'sadness', 'anger', 'fear', 'love', 'joy', 'joy', 'joy', 'joy', 'fear', 'anger', 'surprise', 'sadness', 'sadness', 'anger', 'fear', 'fear', 'sadness', 'joy', 'joy', 'fear', 'sadness', 'sadness', 'joy', 'fear', 'joy', 'joy', 'love', 'anger', 'joy', 'sadness', 'sadness', 'surprise', 'joy', 'surprise', 'joy', 'fear', 'sadness', 'sadness', 'love', 'love', 'joy', 'fear', 'anger', 'joy', 'joy', 'joy', 'joy', 'joy', 'sadness', 'joy', 'sadness', 'sadness', 'sadness', 'joy', 'joy', 'love', 'sadness', 'anger', 'sadness', 'joy', 'joy', 'love', 'sadness', 'joy', 'fear', 'anger', 'anger', 'sadness', 'anger', 'joy', 'joy', 'love', 'fear', 'fear', 'sadness', 'surprise', 'anger', 'anger', 'sadness', 'joy', 'joy', 'joy', 'joy']],

In [80]:
print("folds_val_log  =", folds_val_log)
print("folds_test_log =", folds_test_log)

folds_val_log  = [[[{'eval_loss': 1.0400094985961914, 'eval_emotion_accuracy': 0.7165, 'eval_emotion_weighted_f1': 0.711081, 'eval_emotion_macro_f1': 0.662013, 'eval_main_metric': 0.7165, 'eval_runtime': 14.912, 'eval_samples_per_second': 134.12, 'eval_steps_per_second': 2.146, 'epoch': 37.0, 'best_epoch': 17.0}], [{'eval_loss': 0.9750723838806152, 'eval_emotion_accuracy': 0.767, 'eval_emotion_weighted_f1': 0.761881, 'eval_emotion_macro_f1': 0.70577, 'eval_main_metric': 0.767, 'eval_runtime': 15.4133, 'eval_samples_per_second': 129.758, 'eval_steps_per_second': 2.076, 'epoch': 36.0, 'best_epoch': 16.0}], [{'eval_loss': 1.1994868516921997, 'eval_emotion_accuracy': 0.7415, 'eval_emotion_weighted_f1': 0.719631, 'eval_emotion_macro_f1': 0.656899, 'eval_main_metric': 0.7415, 'eval_runtime': 14.8629, 'eval_samples_per_second': 134.563, 'eval_steps_per_second': 2.153, 'epoch': 51.0, 'best_epoch': 31.0}], [{'eval_loss': 0.7089169025421143, 'eval_emotion_accuracy': 0.7305, 'eval_emotion_weighted_f1': 0.711776, 'eval_emotion_macro_f1': 0.652214, 'eval_main_metric': 0.7305, 'eval_runtime': 16.2139, 'eval_samples_per_second': 123.351, 'eval_steps_per_second': 1.974, 'epoch': 27.0, 'best_epoch': 7.0}], [{'eval_loss': 1.0968165397644043, 'eval_emotion_accuracy': 0.754, 'eval_emotion_weighted_f1': 0.748865, 'eval_emotion_macro_f1': 0.693271, 'eval_main_metric': 0.754, 'eval_runtime': 15.1176, 'eval_samples_per_second': 132.296, 'eval_steps_per_second': 2.117, 'epoch': 34.0, 'best_epoch': 14.0}]]]
folds_test_log = [[[{'eval_loss': 1.0503729581832886, 'eval_emotion_accuracy': 0.7185, 'eval_emotion_weighted_f1': 0.712676, 'eval_emotion_macro_f1': 0.646142, 'eval_main_metric': 0.7185, 'eval_runtime': 14.9184, 'eval_samples_per_second': 134.063, 'eval_steps_per_second': 2.145, 'epoch': 37.0, 'best_epoch': 17.0}], [{'eval_loss': 0.970103919506073, 'eval_emotion_accuracy': 0.7525, 'eval_emotion_weighted_f1': 0.747181, 'eval_emotion_macro_f1': 0.671567, 'eval_main_metric': 0.7525, 'eval_runtime': 15.2013, 'eval_samples_per_second': 131.567, 'eval_steps_per_second': 2.105, 'epoch': 36.0, 'best_epoch': 16.0}], [{'eval_loss': 1.1019575595855713, 'eval_emotion_accuracy': 0.7475, 'eval_emotion_weighted_f1': 0.726563, 'eval_emotion_macro_f1': 0.643731, 'eval_main_metric': 0.7475, 'eval_runtime': 14.9911, 'eval_samples_per_second': 133.412, 'eval_steps_per_second': 2.135, 'epoch': 51.0, 'best_epoch': 31.0}], [{'eval_loss': 0.6917216777801514, 'eval_emotion_accuracy': 0.7205, 'eval_emotion_weighted_f1': 0.701371, 'eval_emotion_macro_f1': 0.619626, 'eval_main_metric': 0.7205, 'eval_runtime': 17.9528, 'eval_samples_per_second': 111.403, 'eval_steps_per_second': 1.782, 'epoch': 27.0, 'best_epoch': 7.0}], [{'eval_loss': 1.036759853363037, 'eval_emotion_accuracy': 0.751, 'eval_emotion_weighted_f1': 0.744842, 'eval_emotion_macro_f1': 0.671892, 'eval_main_metric': 0.751, 'eval_runtime': 15.0591, 'eval_samples_per_second': 132.81, 'eval_steps_per_second': 2.125, 'epoch': 34.0, 'best_epoch': 14.0}]]]

In [81]:
with open(f'results/{EXPERIMENT_NAME.replace(".ipynb", "")}_duration.log', 'w') as f:
    f.write(duration_log)

In [82]:
dataset = get_dataset(Xy_train_tokenized)
dataloader = get_dataloader(dataset, 4)

In [83]:
with torch.no_grad():
    scores = None # (len(X), NUM_CLASSES)
    for batch in dataloader:
        gpu_batch = {k:v.to(device) for k,v in batch.items() if k != 'labels'}
        output = model.generate(**gpu_batch, return_dict_in_generate=True, output_scores=True, max_new_tokens=MAX_NEW_TOKENS, renormalize_logits=True) # output.sequences: (batch_size, seq_len+1!) | output.scores: (seq_len, batch_size, vocab_size)!
        print(torch.min(output.scores[0]))
        break

tensor(-168.2422, device='cuda:0')

# Results

In [84]:
def print_log(folds_log, portion):
    if portion == 'Train':
        color = '\033[1;31m'
    elif portion == 'Validation':
        color = '\033[1;32m'
    elif portion == 'Test':
        color = '\033[1;36m'

    ignored_metrics = ['eval_runtime', 'eval_samples_per_second', 'eval_steps_per_second', 'epoch', 'best_epoch']
    highlighted_metrics = ['eval_bleu_score', 'eval_type_micro_f1', 'eval_polarity_accuracy', 'eval_intensity_accuracy', 'eval_average_of_metrics']

    print(f'{color}{portion}:\033[0m')
    print(f'\033[1mBased on steps with best {METRIC_FOR_BEST_MODEL}\033[0m')

    for metric_name in folds_log[0][0][-1].keys():
        if metric_name in ignored_metrics:
            continue
        metric_values_in_each_fold = []
        for fold_log in folds_log:
            metric_values_in_each_fold.append(np.round([seed_log[-1][metric_name] for seed_log in fold_log], 6).tolist())
        average_metric_values_in_each_fold = np.round(np.mean(metric_values_in_each_fold, axis=1), 6)
        average = np.round(np.mean(average_metric_values_in_each_fold, axis=0), 6)
        print()
        if metric_name in highlighted_metrics:
            print(f'\033[1m{metric_name}:\033[0m {metric_values_in_each_fold}')
            print(f'\033[1meach fold:\033[0m {average_metric_values_in_each_fold}\033[0m')
            print(f'\033[1maverage:  \033[0m {color}{average}\033[0m')
        else:
            print(f'\033[1m{metric_name}:\033[0m {metric_values_in_each_fold}')
            print(f'\033[1meach fold:\033[0m {average_metric_values_in_each_fold}\033[0m')
            print(f'\033[1maverage:\033[0m {average}')

In [85]:
# print_log(folds_train_log, 'Train')

In [86]:
print_log(folds_val_log, 'Validation')

Validation:
Based on steps with best eval_main_metric

eval_loss: [[1.040009, 0.975072, 1.199487, 0.708917, 1.096817]]
each fold: [1.00406]
average: 1.00406

eval_emotion_accuracy: [[0.7165, 0.767, 0.7415, 0.7305, 0.754]]
each fold: [0.7419]
average: 0.7419

eval_emotion_weighted_f1: [[0.711081, 0.761881, 0.719631, 0.711776, 0.748865]]
each fold: [0.730647]
average: 0.730647

eval_emotion_macro_f1: [[0.662013, 0.70577, 0.656899, 0.652214, 0.693271]]
each fold: [0.674033]
average: 0.674033

eval_main_metric: [[0.7165, 0.767, 0.7415, 0.7305, 0.754]]
each fold: [0.7419]
average: 0.7419

In [87]:
print_log(folds_test_log, 'Test')

Test:
Based on steps with best eval_main_metric

eval_loss: [[1.050373, 0.970104, 1.101958, 0.691722, 1.03676]]
each fold: [0.970183]
average: 0.970183

eval_emotion_accuracy: [[0.7185, 0.7525, 0.7475, 0.7205, 0.751]]
each fold: [0.738]
average: 0.738

eval_emotion_weighted_f1: [[0.712676, 0.747181, 0.726563, 0.701371, 0.744842]]
each fold: [0.726527]
average: 0.726527

eval_emotion_macro_f1: [[0.646142, 0.671567, 0.643731, 0.619626, 0.671892]]
each fold: [0.650592]
average: 0.650592

eval_main_metric: [[0.7185, 0.7525, 0.7475, 0.7205, 0.751]]
each fold: [0.738]
average: 0.738

In [88]:
print('\033[1m Early Stopping: \033[0m', end = '')
print(f'{np.round(EARLY_STOPPING, 2)} \n', end='')

print('\033[1m Epochs: \033[0m', end = '')
epochs_in_each_fold = []
for fold_log in folds_val_log:
    epochs_in_each_fold.append(np.round([seed_log[-1]['epoch'] for seed_log in fold_log], 2).tolist())
average_epochs_in_each_fold = np.round(np.mean(epochs_in_each_fold, axis=0), 2)
average = np.round(np.mean(average_epochs_in_each_fold, axis=0), 2)
print(f'{average} ', end='')
print(f'  \t\t\t\t\t\t raw: {epochs_in_each_fold}')

print('\033[1m Epoch in Which the Best Results Were Achieved: \033[0m', end = '')
best_epoch_in_each_fold = []
for fold_log in folds_val_log:
    best_epoch_in_each_fold.append(np.round([seed_log[-1]['best_epoch'] for seed_log in fold_log], 2).tolist())
average_best_epoch_in_each_fold = np.round(np.mean(best_epoch_in_each_fold, axis=0), 2)
average = np.round(np.mean(average_best_epoch_in_each_fold, axis=0), 2)
print(f'{average} ', end='')
print(f'  \t raw: {best_epoch_in_each_fold}')

 Early Stopping: 20
 Epochs: 37.0   						 raw: [[37.0, 36.0, 51.0, 27.0, 34.0]]
 Epoch in Which the Best Results Were Achieved: 17.0   	 raw: [[17.0, 16.0, 31.0, 7.0, 14.0]]

# Save/Load model to/from Google Drive

### Save

In [89]:
# torch.save(model.state_dict(), path)

### Load

In [90]:
# model.load_state_dict(torch.load(path))

In [91]:
# from google.colab import drive
# drive.mount('/content/gdrive')

In [92]:
# model_save_name = 'a_great_name'

# path = f'/content/gdrive/MyDrive/MPQA/models/{model_save_name}'

# Error Analysis

In [93]:
%mkdir results/preds

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [94]:
# Extract X_val_type from input

X_val_type = None
if DATASET_NAME in ['MPQA-P', 'MPQA-I']:
    X_val_type = [x.split(' | ')[0] for x in X_val]

In [95]:
if SHOW_VAL_PREDICTIONS == True:

    candidates_val = preds_texts_val_list[0][0][-1]
    referenceses_val = merge_samples(X_val, targets_texts_val_list[0])
    squeezed_X, squeezed_candidates, squeezed_referenceses = squeeze_samples(X_val, candidates_val, referenceses_val)

    with open(f'results/preds/{EXPERIMENT_NAME}_val_predictions.txt', 'w') as f:
        if RUNTIME_TYPE == 'CONDA':
            original_stdout = sys.stdout # Save a reference to the original standard output
            sys.stdout = f # Change the standard output to the file we created.

        CNT = 0
        for i in range(len(squeezed_X)):
            # if candidates[i] not in referenceses[i]:
            CNT += 1
            print(f'\n#{CNT}')
            print(f'┌X: {repr(squeezed_X[i])}')
            print(f'├C: {repr(squeezed_candidates[i])}')
            print(f'└R: {squeezed_referenceses[i]}')

        if RUNTIME_TYPE == 'CONDA':
            sys.stdout = original_stdout # Reset the standard output to its original value

In [96]:
# Store raw outputs

with open(f'results/preds/{EXPERIMENT_NAME}_raw_val_predictions.txt', 'w') as f:
    original_stdout = sys.stdout # Save a reference to the original standard output
    sys.stdout = f # Change the standard output to the file we created.

    print('X_val =', X_val)
    print('preds_texts_val_list =', preds_texts_val_list)
    print('targets_texts_val_list =', targets_texts_val_list)

    sys.stdout = original_stdout # Reset the standard output to its original value

In [97]:
# Store sampled Data

with open(f'results/preds/{EXPERIMENT_NAME}_sampled_data.txt', 'w') as f:
    original_stdout = sys.stdout # Save a reference to the original standard output
    sys.stdout = f # Change the standard output to the file we created.

    for fold_counter in range(MAX_FOLDS):
        print(f'█████ FOLD: {fold_counter}/{MAX_FOLDS-1} ████████████████████████████████████████████████████████████████')
        for seed_counter in range(REPEAT_SAMPLING):
            print(f'════╡ {fold_counter} ╞═╡ SEED: {seed_counter}/{REPEAT_SAMPLING-1} ╞═════════════════════════════════════════════════════════')
            for sampling_iteration in range(SAMPLING_ITERATIONS):
                print(f'────┤ {fold_counter} ├─┤ {seed_counter} ├─┤ ITER: {sampling_iteration}/{SAMPLING_ITERATIONS-1} ├───────────────────────────────────────────────────')
                Xs, ys = sampled_list[fold_counter][seed_counter][sampling_iteration]
                for ax, ay in zip(Xs, ys):
                    print(f'┌X: {repr(ax)}')
                    print(f'└y: {repr(ay)}')

    sys.stdout = original_stdout # Reset the standard output to its original value

In [98]:
if DATASET_NAME == 'MPQA-T':
    targets_vecs = outputs_text_to_vec(targets_texts_val_list[0])
    preds_vecs   = outputs_text_to_vec(preds_texts_val_list[0][0][-1])

    count_targets = np.sum(np.sum(targets_vecs[:, :NUM_TYPE_CLASSES], axis=1) > 1)
    count_preds   = np.sum(np.sum(preds_vecs[:, :NUM_TYPE_CLASSES], axis=1) > 1)

    print(f' Actual multi-type samples:    {count_targets}\n Predicted multi-type samples: {count_preds}')

In [99]:
if DATASET_NAME == 'MPQA-I':
    preds_vecs = outputs_text_to_vec(preds_texts_val_list[0][0][-1])
    for i in range(len(preds_vecs)):
        if (preds_vecs[i] == [1, 0, 1]).all():
            print(i, preds_vecs[i])
        if (preds_vecs[i] == [1, 0, 1]).all():
            print(i, preds_vecs[i])
        if (preds_vecs[i] == [0, 0, 0]).all():
            print(i, preds_vecs[i])

# Store Results

In [100]:
def clean_the_metric_name(name):
    return name.\
        replace("eval_", "").\
        replace("_", " ").\
        replace("type", "T").\
        replace("polarity", "P").\
        replace("intensity", "I").\
        replace("accuracy", "ACC").\
        replace("exact match ratio", "EMR").\
        replace("f1", "F1").\
        replace("micro ", "").\
        replace("weighted", "").\
        replace("average of metrics", "AVG")

if STORE_RESULTS != []:
    if not os.path.exists('results.csv'):
        with open(f'results.csv', 'w') as f:
            original_stdout = sys.stdout # Save a reference to the original standard output
            sys.stdout = f # Change the standard output to the file we created.

            print('Experiment Name, ', end='')
            print('Iter, ', end='')
            print('║, ', end='')

            for split in ['val', 'tst']:
                first_metric = True
                for metric_name in STORE_RESULTS:
                    if first_metric:
                        first_metric = False
                    else:
                        print('│, ', end='')
                    print(f'{split} {clean_the_metric_name(metric_name)}, ', end='')
                    for fold_counter in range(MAX_FOLDS):
                        if MAX_FOLDS > 1:
                            print('|, ', end='')
                            print(f'fold{fold_counter+1}, ', end='')
                        if REPEAT_SAMPLING > 1:
                            print('|, ', end='')
                            for seed_counter in range(REPEAT_SAMPLING):
                                print(f'seed{seed_counter}, ', end='')
                print('║, ', end='')

            print(f'earlystopping, ', end='')
            print(f'epochs, ', end='')
            print(f'best epoch ', end = '')
            print()

            sys.stdout = original_stdout # Reset the standard output to its original value

    with open(f'results.csv', 'a') as f:
        original_stdout = sys.stdout # Save a reference to the original standard output
        sys.stdout = f # Change the standard output to the file we created.

        for sampling_iteration in range(SAMPLING_ITERATIONS):
            print(f'{EXPERIMENT_NAME.replace(".ipynb", "").replace("_", " ").replace(",", ".")}, ', end='')
            print(f'{sampling_iteration}, ', end='')
            print(f'║, ', end='')

            for split in [folds_val_log, folds_test_log]:
                first_metric = True
                for metric_name in STORE_RESULTS:
                    if first_metric:
                        first_metric = False
                    else:
                        print('│, ', end='')
                    if metric_name in folds_val_log[0][0][sampling_iteration]:
                        metric_values = np.array([[split[fold_counter][seed_counter][sampling_iteration][metric_name] for seed_counter in range(REPEAT_SAMPLING)] for fold_counter in range(MAX_FOLDS)])
                        print(f'{np.round(np.mean(metric_values), 6)}, ', end='')
                        for fold_counter in range(MAX_FOLDS):
                            if MAX_FOLDS > 1:
                                print('|, ', end='')
                                print(f'{np.round(np.mean(metric_values[fold_counter]), 6)}, ', end='')
                            if REPEAT_SAMPLING > 1:
                                print('|, ', end='')
                                for seed_counter in range(REPEAT_SAMPLING):
                                    print(f'{np.round(metric_values[fold_counter][seed_counter], 6)}, ', end='')
                    else:
                        for i in range(MAX_FOLDS*REPEAT_SAMPLING + MAX_FOLDS + 1):
                            print('-, ', end='')
                            for fold_counter in range(MAX_FOLDS):
                                if MAX_FOLDS > 1:
                                    print('|, ', end='')
                                    print('-, ', end='')
                                if REPEAT_SAMPLING > 1:
                                    print('|, ', end='')
                                    for seed_counter in range(REPEAT_SAMPLING):
                                        print('-, ', end='')
                print('║, ', end='')

            print(f'{np.round(EARLY_STOPPING, 2)}, ', end='')

            epochs = [folds_val_log[fold_counter][seed_counter][sampling_iteration]['epoch'] for fold_counter, seed_counter in itertools.product(range(MAX_FOLDS), range(REPEAT_SAMPLING))]
            average = np.round(np.mean(epochs, axis=0), 2)
            print(f'{average}, ', end='')

            best_epochs = [folds_val_log[fold_counter][seed_counter][sampling_iteration]['best_epoch'] for fold_counter, seed_counter in itertools.product(range(MAX_FOLDS), range(REPEAT_SAMPLING))]
            average = np.round(np.mean(best_epochs, axis=0), 2)
            print(f'{average} ', end='')

            print()

        sys.stdout = original_stdout # Reset the standard output to its original value

In [101]:
print_log(folds_test_log, 'Test')

Test:
Based on steps with best eval_main_metric

eval_loss: [[1.050373, 0.970104, 1.101958, 0.691722, 1.03676]]
each fold: [0.970183]
average: 0.970183

eval_emotion_accuracy: [[0.7185, 0.7525, 0.7475, 0.7205, 0.751]]
each fold: [0.738]
average: 0.738

eval_emotion_weighted_f1: [[0.712676, 0.747181, 0.726563, 0.701371, 0.744842]]
each fold: [0.726527]
average: 0.726527

eval_emotion_macro_f1: [[0.646142, 0.671567, 0.643731, 0.619626, 0.671892]]
each fold: [0.650592]
average: 0.650592

eval_main_metric: [[0.7185, 0.7525, 0.7475, 0.7205, 0.751]]
each fold: [0.738]
average: 0.738

In [102]:
print_log(folds_val_log, 'Validation')

Validation:
Based on steps with best eval_main_metric

eval_loss: [[1.040009, 0.975072, 1.199487, 0.708917, 1.096817]]
each fold: [1.00406]
average: 1.00406

eval_emotion_accuracy: [[0.7165, 0.767, 0.7415, 0.7305, 0.754]]
each fold: [0.7419]
average: 0.7419

eval_emotion_weighted_f1: [[0.711081, 0.761881, 0.719631, 0.711776, 0.748865]]
each fold: [0.730647]
average: 0.730647

eval_emotion_macro_f1: [[0.662013, 0.70577, 0.656899, 0.652214, 0.693271]]
each fold: [0.674033]
average: 0.674033

eval_main_metric: [[0.7165, 0.767, 0.7415, 0.7305, 0.754]]
each fold: [0.7419]
average: 0.7419

# Timer

In [103]:
# Time data

end_time = datetime.now() # end timer

print('\033[1mStart:\033[0m {}'.format(start_time))
print('\033[1mEnd:\033[0m {}'.format(end_time))
print('\n\033[1mDuration:\033[0m {}'.format(end_time - start_time))

Start: 2026-03-20 15:51:20.914972
End: 2026-03-20 16:55:48.115377

Duration: 1:04:27.200405